import { Controller } from "@nestjs/common";
import { TypedRoute, TypedParam, TypedBody } from "@nestia/core";
import typia, { tags } from "typia";

;
import { IShoppingMemberEmail } from "../../../../api/structures/IShoppingMemberEmail";

;
@Controller("/shopping/members/:memberId/emails")
export class ShoppingMembersEmailsController {
    /**
     * Registers a new email address for a given member. Can be used for login, recovery, or notifications. Supports multiple emails per member.
     *
     * @param memberId Unique identifier of the member.
     * @param body Registers a new email address for a given member. Can be used for login, recovery, or notifications. Supports multiple emails per member.
     * @nestia Generated by Nestia - https://github.com/samchon/nestia
    */
    @TypedRoute.Post()
    public async postByMemberid(
    @TypedParam("memberId")
    memberId: string & tags.Format<"uuid">, 
    @TypedBody()
    body: IShoppingMemberEmail.ICreate): Promise<IShoppingMemberEmail> {
        memberId;
        body;
        return typia.random<IShoppingMemberEmail>();
    }
}
