import { Controller } from "@nestjs/common";
import { TypedRoute, TypedParam } from "@nestia/core";
import typia, { tags } from "typia";

;
import { IShoppingSaleSnapshot_alt__agt_ } from "../../../../api/structures/IShoppingSaleSnapshot_alt__agt_";

;
@Controller("/shopping/sales/:saleId/snapshots")
export class ShoppingSalesSnapshotsController {
    /**
     * Lists all snapshots (versions) for a product/sale, ordered chronologically. Used for history/audit/viewing and comparing previous states.
     *
     * @param saleId Unique identifier of the sale/product.
     * @nestia Generated by Nestia - https://github.com/samchon/nestia
    */
    @TypedRoute.Get()
    public async getBySaleid(
    @TypedParam("saleId")
    saleId: string & tags.Format<"uuid">): Promise<IShoppingSaleSnapshot_alt__agt_> {
        saleId;
        return typia.random<IShoppingSaleSnapshot_alt__agt_>();
    }
}
