import { Controller } from "@nestjs/common";
import { TypedRoute, TypedBody } from "@nestia/core";
import typia from "typia";

;
import { IShoppingCoupon } from "../../../api/structures/IShoppingCoupon";

;
@Controller("/shopping/coupons")
export class ShoppingCouponsController {
    /**
     * Issues a new discount coupon, specifying conditions, limits, and time windows. Supports public or code-based distribution.
     *
     * @param body Issues a new discount coupon, specifying conditions, limits, and time windows. Supports public or code-based distribution.
     * @nestia Generated by Nestia - https://github.com/samchon/nestia
    */
    @TypedRoute.Post()
    public async post(
    @TypedBody()
    body: IShoppingCoupon.ICreate): Promise<IShoppingCoupon> {
        body;
        return typia.random<IShoppingCoupon>();
    }
}
