import { AutoBeOpenApi } from "@autobe/interface";

export interface IAutoBeInterfaceSchemasReviewApplication {
  /**
   * Reviews and validates OpenAPI schema definitions for compliance and
   * quality.
   *
   * This function performs comprehensive validation of schemas generated by the
   * INTERFACE_SCHEMA agent, checking for security violations, structural
   * issues, relationship correctness, and database consistency.
   *
   * The review process identifies violations, applies fixes automatically, and
   * returns modified schemas along with detailed analysis.
   *
   * @param props Review results including analysis, action plan, and modified
   *   schemas
   */
  review: (props: IAutoBeInterfaceSchemasReviewApplication.IProps) => void;
}

export namespace IAutoBeInterfaceSchemasReviewApplication {
  /**
   * Output structure for the schema review function.
   *
   * Contains the review analysis, action plan, and modified schema definitions
   * produced during the validation process.
   */
  export interface IProps {
    /** Analysis and planning information generated during review. */
    think: IThink;

    /**
     * Modified schemas resulting from the review process.
     *
     * Contains only the schemas that were actively modified during review (not
     * all input schemas). This enables efficient change tracking and merge
     * operations.
     *
     * - Include a schema if it was created, modified, renamed, or had properties
     *   added/removed/changed
     * - Exclude schemas that passed validation without any modifications
     * - Return empty object {} when all schemas are compliant and no changes were
     *   needed
     */
    content: Record<string, AutoBeOpenApi.IJsonSchemaDescriptive>;
  }

  export interface IThink {
    /**
     * Analysis findings from the schema review process.
     *
     * Documents violations found during validation, organized by severity and
     * category. Includes specific schema names and rule violations.
     *
     * Should state "No issues found." when all schemas pass validation without
     * violations.
     */
    review: string;

    /**
     * Action plan describing fixes applied to resolve identified issues.
     *
     * Lists all modifications made during the review process, categorized by
     * priority and type of fix.
     *
     * Should state "No improvements required. All schemas meet AutoBE
     * standards." when no modifications were necessary.
     */
    plan: string;
  }
}
