import { AutoBeOpenApi } from "@autobe/interface";

export interface IAutoBeInterfaceSchemasReviewApplication {
  review: (props: IAutoBeInterfaceSchemasReviewApplication.IProps) => void;
}

export namespace IAutoBeInterfaceSchemasReviewApplication {
  /**
   * Properties generated by the LLM for schema review and improvement.
   *
   * These properties are created by the Interface Schemas Review Agent and will
   * be published as part of the AutoBeInterfaceSchemasReviewEvent to track the
   * schema validation and enhancement process.
   */
  export interface IProps {
    /**
     * Review analysis generated by the LLM.
     *
     * Contains the Interface Schemas Review Agent's detailed assessment of the
     * original schemas, including validation results, identified issues, and
     * quality evaluation. This review guides the subsequent improvement plan.
     */
    review: string;

    /**
     * Improvement plan generated by the LLM.
     *
     * The structured plan created by the Interface Schemas Review Agent
     * outlining specific modifications to be applied to the schemas. If no
     * changes are needed, explicitly states that the schemas are acceptable
     * as-is.
     */
    plan: string;

    /**
     * Enhanced schemas generated by the LLM.
     *
     * The final OpenAPI schemas produced by the Interface Schemas Review Agent
     * after applying all improvements from the plan. If no modifications were
     * necessary, contains the original schemas unchanged. These schemas will be
     * used for API endpoint generation in subsequent phases.
     */
    content: Record<
      string,
      AutoBeOpenApi.IJsonSchemaDescriptive<AutoBeOpenApi.IJsonSchema>
    >;
  }
}
