import { IAgenticaHistoryJson } from "@agentica/core";
import { AutoBeAnalyzeHistory, AutoBePrisma } from "@autobe/interface";
import { v4 } from "uuid";

import { AutoBeSystemPromptConstant } from "../../constants/AutoBeSystemPromptConstant";

export const transformPrismaSchemaHistories = (
  analyze: AutoBeAnalyzeHistory,
  component: AutoBePrisma.IComponent,
  otherComponents: AutoBePrisma.IComponent[],
): Array<
  IAgenticaHistoryJson.IAssistantMessage | IAgenticaHistoryJson.ISystemMessage
> => {
  return [
    {
      id: v4(),
      created_at: new Date().toISOString(),
      type: "systemMessage",
      text: AutoBeSystemPromptConstant.PRISMA_SCHEMA,
    },
    {
      id: v4(),
      created_at: new Date().toISOString(),
      type: "systemMessage",
      text: [
        "Here is the requirement analysis report.",
        "",
        "Call the provided tool function to generate Prisma DB schema",
        "referencing below requirement analysis report.",
        "",
        "## User Request",
        analyze.reason,
        "",
        `## Requirement Analysis Report`,
        "",
        "```json",
        JSON.stringify(analyze.files),
        "```",
        "",
        "## Target Component to Make",
        "",
        "**MANDATORY: CREATE ALL THESE TABLES**",
        "",
        "You must create models for EVERY table listed in the target component.",
        "This is your assigned domain - implement all tables completely.",
        "",
        "✅ **MUST DO:**",
        "- Create models for ALL tables in the target component",
        "- Use exact table names as specified (converted to plural snake_case)",
        "- Implement all required fields, relationships, and indexes",
        "- Stay within this domain's business scope",
        "",
        "❌ **NEVER DO:**",
        "- Omit any required tables from the target component",
        "- Rename tables or change their specified names",
        "- Create tables that belong to other domains",
        "",
        "```json",
        JSON.stringify(component),
        "```",
        "",
        "## Other Components to Reference",
        "",
        "**CRITICAL: DO NOT CREATE THESE TABLES**",
        "",
        "The following components contain tables that already exist in other schema files.",
        "You must ONLY use these for foreign key references and relationships.",
        "",
        "❌ **NEVER DO:**",
        "- Create models for any tables listed in other components",
        "- Duplicate or recreate existing tables from other domains",
        "- Add tables that belong to other business domains",
        "",
        "✅ **ALWAYS DO:**",
        "- Reference these tables in foreign key relationships only",
        "- Use exact table names when creating foreign key fields",
        "- Respect domain boundaries and don't invade other domains",
        "",
        "```json",
        JSON.stringify(otherComponents),
        "```",
        "",
        "## VALIDATION CHECKPOINT",
        "",
        "Before submitting, verify:",
        "- [ ] All tables from target component are included",
        "- [ ] No tables from other components are created",
        "- [ ] All foreign key references point to existing tables",
        "- [ ] Domain boundaries are respected",
      ].join("\n"),
    },
  ];
};
