packages:
  - packages/*
  - '!packages/compiler-dependencies'
  - test
  - website
catalogs:
  typescript:
    ts-node: ^10.9.2
    ts-patch: ^3.3.0
    typescript: ~5.8.3
  agentica:
    "@samchon/openapi": ^4.2.0
    "@agentica/core": ^0.21.0
    "@agentica/rpc": ^0.21.0
    openai: ^4.80.0
    typia: ^9.1.1
  nestia:
    "@nestia/benchmark": ^6.0.3
    "@nestia/core": ^6.0.3
    "@nestia/e2e": ^6.0.3
    "@nestia/fetcher": ^6.0.3
    "@nestia/migrate": ^6.0.3
    "@nestia/sdk": ^6.0.3
