packages:
  - packages/*
  - '!packages/compiler-dependencies'
  - test
  - website
catalogs:
  agentica:
    "@agentica/core": ^0.25.0
    "@agentica/rpc": ^0.25.0
  nestia:
    "@nestia/benchmark": ^6.0.3
    "@nestia/core": ^6.0.3
    "@nestia/e2e": ^6.0.3
    "@nestia/fetcher": ^6.0.3
    "@nestia/migrate": ^6.0.3
    "@nestia/sdk": ^6.0.3
  samchon:
    "@samchon/openapi": ^4.3.0
    prisma-markdown: ^3.0.0
    tgrid: ^1.1.0
    tstl: ^3.0.0
    typia: ^9.3.0
  typescript:
    ts-node: ^10.9.2
    ts-patch: ^3.3.0
    typescript: ~5.8.3
  libs:
    openai: ^4.80.0