/**
 * @packageDocumentation
 * @module api.functional.autobe.playground.config
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IAutoBePlaygroundConfig } from "@autobe/interface";
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";

/**
 * Get the global playground configuration.
 *
 * Returns the singleton configuration record containing default locale,
 * timezone, and optional default vendor/model for frontend pre-fill.
 *
 * @author Samchon
 * @returns Current global configuration
 * @tag Config
 *
 * @controller AutoBePlaygroundConfigController.get
 * @path GET /autobe/playground/config
 * @accessor api.functional.autobe.playground.config.get
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function get(connection: IConnection): Promise<get.Output> {
  return PlainFetcher.fetch(connection, {
    ...get.METADATA,
    template: get.METADATA.path,
    path: get.path(),
  });
}
export namespace get {
  export type Output = IAutoBePlaygroundConfig;

  export const METADATA = {
    method: "GET",
    path: "/autobe/playground/config",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/autobe/playground/config";
}

/**
 * Update the global playground configuration.
 *
 * Only provided fields are updated. Omitted fields retain their current
 * values.
 *
 * @param body Fields to update
 * @author Samchon
 * @returns Updated global configuration
 * @tag Config
 *
 * @controller AutoBePlaygroundConfigController.update
 * @path PUT /autobe/playground/config
 * @accessor api.functional.autobe.playground.config.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(),
    },
    body,
  );
}
export namespace update {
  export type Body = IAutoBePlaygroundConfig.IUpdate;
  export type Output = IAutoBePlaygroundConfig;

  export const METADATA = {
    method: "PUT",
    path: "/autobe/playground/config",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/autobe/playground/config";
}
