/**
 * @module api.functional.autobe.hackathon.participants.sessions
 * @packageDocumentation
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IAutoBeHackathonSession, IPage } from "@autobe/hackathon-api";
import type { IAutoBeRpcListener, IAutoBeRpcService } from "@autobe/interface";
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Driver } from "tgrid";
import { WebSocketConnector } from "tgrid";
import type { Primitive, tags } from "typia";

/**
 * @controller AutoBeHackathonParticipantSessionController.index
 * @path PATCH /autobe/hackathon/:hackathonCode/participants/sessions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  hackathonCode: string,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(hackathonCode),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IPage.IRequest>;
  export type Output = Primitive<IPage<IAutoBeHackathonSession.ISummary>>;

  export const METADATA = {
    method: "PATCH",
    path: "/autobe/hackathon/:hackathonCode/participants/sessions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (hackathonCode: string) =>
    `/autobe/hackathon/${encodeURIComponent(hackathonCode?.toString() ?? "null")}/participants/sessions`;
}

/**
 * @controller AutoBeHackathonParticipantSessionController.at
 * @path GET /autobe/hackathon/:hackathonCode/participants/sessions/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  hackathonCode: string,
  id: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(hackathonCode, id),
  });
}
export namespace at {
  export type Output = Primitive<IAutoBeHackathonSession>;

  export const METADATA = {
    method: "GET",
    path: "/autobe/hackathon/:hackathonCode/participants/sessions/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    hackathonCode: string,
    id: string & tags.Format<"uuid">,
  ) =>
    `/autobe/hackathon/${encodeURIComponent(hackathonCode?.toString() ?? "null")}/participants/sessions/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller AutoBeHackathonParticipantSessionController.review
 * @path PUT /autobe/hackathon/:hackathonCode/participants/sessions/:id/review
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function review(
  connection: IConnection,
  hackathonCode: string,
  id: string & tags.Format<"uuid">,
  body: review.Body,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...review.METADATA,
      template: review.METADATA.path,
      path: review.path(hackathonCode, id),
    },
    body,
  );
}
export namespace review {
  export type Body = Primitive<IAutoBeHackathonSession.IReview>;

  export const METADATA = {
    method: "PUT",
    path: "/autobe/hackathon/:hackathonCode/participants/sessions/:id/review",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    hackathonCode: string,
    id: string & tags.Format<"uuid">,
  ) =>
    `/autobe/hackathon/${encodeURIComponent(hackathonCode?.toString() ?? "null")}/participants/sessions/${encodeURIComponent(id?.toString() ?? "null")}/review`;
}

/**
 * @controller AutoBeHackathonParticipantSessionSocketController.start
 * @path /autobe/hackathon/:hackathonCode/participants/sessions/start
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function start(
  connection: IConnection<start.Header>,
  hackathonCode: string,
  provider: start.Provider,
): Promise<start.Output> {
  const connector: WebSocketConnector<
    start.Header,
    start.Provider,
    start.Listener
  > = new WebSocketConnector(connection.headers ?? ({} as any), provider);
  await connector.connect(
    `${connection.host.endsWith("/") ? connection.host.substring(0, connection.host.length - 1) : connection.host}${start.path(hackathonCode)}`,
  );
  const driver: Driver<start.Listener> = connector.getDriver();
  return {
    connector,
    driver,
  };
}
export namespace start {
  export type Output = {
    connector: WebSocketConnector<Header, Provider, Listener>;
    driver: Driver<Listener>;
  };
  export type Header = IAutoBeHackathonSession.IStartHeader;
  export type Provider = IAutoBeRpcListener;
  export type Listener = IAutoBeRpcService;

  export const path = (hackathonCode: string) =>
    `/autobe/hackathon/${encodeURIComponent(hackathonCode?.toString() ?? "null")}/participants/sessions/start`;
}

/**
 * @controller AutoBeHackathonParticipantSessionSocketController.restart
 * @path /autobe/hackathon/:hackathonCode/participants/sessions/:id/restart
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function restart(
  connection: IConnection<restart.Header>,
  hackathonCode: string,
  id: string & tags.Format<"uuid">,
  provider: restart.Provider,
): Promise<restart.Output> {
  const connector: WebSocketConnector<
    restart.Header,
    restart.Provider,
    restart.Listener
  > = new WebSocketConnector(connection.headers ?? ({} as any), provider);
  await connector.connect(
    `${connection.host.endsWith("/") ? connection.host.substring(0, connection.host.length - 1) : connection.host}${restart.path(hackathonCode, id)}`,
  );
  const driver: Driver<restart.Listener> = connector.getDriver();
  return {
    connector,
    driver,
  };
}
export namespace restart {
  export type Output = {
    connector: WebSocketConnector<Header, Provider, Listener>;
    driver: Driver<Listener>;
  };
  export type Header = IAutoBeHackathonSession.IRestartHeader;
  export type Provider = IAutoBeRpcListener;
  export type Listener = IAutoBeRpcService;

  export const path = (
    hackathonCode: string,
    id: string & tags.Format<"uuid">,
  ) =>
    `/autobe/hackathon/${encodeURIComponent(hackathonCode?.toString() ?? "null")}/participants/sessions/${encodeURIComponent(id?.toString() ?? "null")}/restart`;
}

/**
 * @controller AutoBeHackathonParticipantSessionSocketController.replay
 * @path /autobe/hackathon/:hackathonCode/participants/sessions/:id/replay
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function replay(
  connection: IConnection<replay.Header>,
  hackathonCode: string,
  id: string & tags.Format<"uuid">,
  provider: replay.Provider,
): Promise<replay.Output> {
  const connector: WebSocketConnector<
    replay.Header,
    replay.Provider,
    replay.Listener
  > = new WebSocketConnector(connection.headers ?? ({} as any), provider);
  await connector.connect(
    `${connection.host.endsWith("/") ? connection.host.substring(0, connection.host.length - 1) : connection.host}${replay.path(hackathonCode, id)}`,
  );
  const driver: Driver<replay.Listener> = connector.getDriver();
  return {
    connector,
    driver,
  };
}
export namespace replay {
  export type Output = {
    connector: WebSocketConnector<Header, Provider, Listener>;
    driver: Driver<Listener>;
  };
  export type Header = IAutoBeHackathonSession.IReplayHeader;
  export type Provider = IAutoBeRpcListener;
  export type Listener = IAutoBeRpcService;

  export const path = (
    hackathonCode: string,
    id: string & tags.Format<"uuid">,
  ) =>
    `/autobe/hackathon/${encodeURIComponent(hackathonCode?.toString() ?? "null")}/participants/sessions/${encodeURIComponent(id?.toString() ?? "null")}/replay`;
}
