import { default as unplugin } from "@ryoppippi/unplugin-typia";
import { defineConfig } from "tsdown";

export default defineConfig({
  entry: "./src/index.ts",
  outDir: "./dist",
  target: "es2022",
  platform: "node",
  clean: true,
  shims: true,
  sourcemap: true,
  noExternal: [
    "@samchon/openapi",
    "@samchon/openapi/lib/converters/OpenApiV3_1Emender",
    "@samchon/openapi/lib/composers/LlmSchemaComposer",
    "@samchon/openapi/lib/converters/OpenApiV3Downgrader",
    "@samchon/openapi/lib/utils/OpenApiExclusiveEmender",
    "@autobe/compiler",
    "@autobe/agent",
    "@autobe/rpc",
    "@agentica/core",
    "openai",
    "tgrid",
    "typia",
    "typia/lib/utils/NamingConvention",
    "typia/lib/transform",
    "typia/lib/utils/Escaper",
    "typia/lib/factories/ExpressionFactory",
    "typia/lib/internal/_validateReport.js",
    "typia/lib/internal/_accessExpressionAsString.js",
    "typia/lib/internal/_llmApplicationFinalize.js",
    "typia/lib/internal/_isUniqueItems.js",
    "typia/lib/internal/_assertGuard.js",
    "typia/lib/programmers/ImportProgrammer",
    "typia/lib/factories/MetadataCollection",
    "typia/lib/factories/MetadataFactory",
    "typia/lib/programmers/http/HttpQueryProgrammer",
    "typia/lib/programmers/llm/LlmSchemaProgrammer",
    "typia/lib/transformers/TransformerError",
  ],
  plugins: [unplugin.rollup()],
});
