import * as path from "path";

import type { AgentResult } from "../agents";
import type { EvaluationResult, Issue, PhaseResult } from "../types";
import { AGENT_WEIGHT_RATIO, PHASE_NAMES, PHASE_WEIGHTS } from "../types";

interface ExtendedResult extends EvaluationResult {
  agentEvaluations?: AgentResult[];
}

/** Display weights derived from PHASE_WEIGHTS (auto-normalized to 100%) */
const SCORING_PHASE_KEYS = [
  "documentQuality",
  "requirementsCoverage",
  "testCoverage",
  "logicCompleteness",
  "apiCompleteness",
] as const;
const baseSum = SCORING_PHASE_KEYS.reduce(
  (sum, k) => sum + PHASE_WEIGHTS[k],
  0,
);
const WEIGHTS: Record<string, string> = Object.fromEntries(
  SCORING_PHASE_KEYS.map((k) => [
    k,
    `${Math.round((PHASE_WEIGHTS[k] / baseSum) * 100)}%`,
  ]),
);

/** Maximum number of issues to display in a table before truncating */
const MAX_DISPLAY_ISSUES = 20;

const SCORING_PHASES = SCORING_PHASE_KEYS;

export function generateMarkdownReport(result: ExtendedResult): string {
  return `
# AutoBE Code Evaluation Report

**Generated:** ${result.meta.evaluatedAt}
**Target:** ${result.targetPath}
**Files Evaluated:** ${result.meta.evaluatedFiles}
**Duration:** ${result.meta.totalDurationMs}ms

${renderOverallScore(result)}

${renderScoringPhases(result)}

${renderDetailedResults(result)}

${renderReferenceInfo(result)}

${renderAgentEvaluations(result.agentEvaluations)}

${renderSummary(result)}

---
*Generated by @autobe/estimate v${result.meta.estimateVersion}*
`.trim();
}

function renderOverallScore(result: ExtendedResult): string {
  const agents = result.agentEvaluations;
  const hasAgents = agents && agents.length > 0;

  let breakdown = "";
  if (hasAgents) {
    const phaseScore = Math.round(
      SCORING_PHASE_KEYS.reduce(
        (sum, key) =>
          sum +
          ((result.phases[key as keyof typeof result.phases] as PhaseResult)
            .score *
            PHASE_WEIGHTS[key]) /
            baseSum,
        0,
      ) * 100,
    );
    const agentAvg =
      agents.reduce((sum, a) => sum + a.score, 0) / agents.length;
    const phaseW = 1 - AGENT_WEIGHT_RATIO;

    breakdown = `
### Score Breakdown

| Component | Score | Weight | Contribution |
|-----------|-------|--------|-------------|
| Phase Score | ${phaseScore}/100 | ${Math.round(phaseW * 100)}% | ${(phaseScore * phaseW).toFixed(1)} |
| Agent Score | ${agentAvg.toFixed(1)}/100 | ${Math.round(AGENT_WEIGHT_RATIO * 100)}% | ${(agentAvg * AGENT_WEIGHT_RATIO).toFixed(1)} |
| **Total** | | | **${result.totalScore}/100** |
`;
  }

  return `
## Overall Score

| Grade | Score |
|-------|-------|
| **${result.grade}** | **${result.totalScore}/100** |

${breakdown}
`.trim();
}

function renderScoringPhases(result: ExtendedResult): string {
  const gateStatus = result.phases.gate.passed ? "✅ Pass" : "❌ Fail";

  const phaseRows = SCORING_PHASES.map((phase) => {
    const phaseResult = result.phases[phase];
    const phaseName = PHASE_NAMES[phase];
    const weight = WEIGHTS[phase];
    const status = getStatusEmoji(
      phaseResult.score,
      phaseResult.metrics?.skipped as boolean,
    );
    return `| ${phaseName} | ${phaseResult.score}/100 | ${weight} | ${status} |`;
  }).join("\n");

  // Golden Set row (optional — only present with --golden --run-tests)
  const goldenRow = result.phases.goldenSet
    ? `| ${PHASE_NAMES.goldenSet} | ${result.phases.goldenSet.score}/100 | ${Math.round(PHASE_WEIGHTS.goldenSet * 100)}% | ${getStatusEmoji(result.phases.goldenSet.score)} |`
    : "";

  return `
## Scoring Phases (affects total score)

| Phase | Score | Weight | Status |
|-------|-------|--------|--------|
| Gate | - | - | ${gateStatus} |
${phaseRows}
${goldenRow}
`.trim();
}

function renderDetailedResults(result: ExtendedResult): string {
  const gateIssues = result.phases.gate.issues;
  const gateCritical = gateIssues.filter((i) => i.severity === "critical");
  const gateWarning = gateIssues.filter((i) => i.severity === "warning");
  const gateSuggestion = gateIssues.filter((i) => i.severity === "suggestion");

  let gateSection: string;
  if (!result.phases.gate.passed) {
    gateSection = `❌ Gate validation failed.\n\n**Issues:**\n${gateIssues.map((i) => `- [${i.code}] ${i.message}`).join("\n")}`;
  } else if (gateIssues.length === 0) {
    gateSection = "✅ All basic validations passed.";
  } else {
    gateSection = `✅ Gate passed with ${gateIssues.length} issue(s) (${gateCritical.length} critical, ${gateWarning.length} warnings, ${gateSuggestion.length} suggestions)`;
    const gateNonSuggestions = gateIssues.filter(
      (i) => i.severity !== "suggestion",
    );
    if (gateNonSuggestions.length > 0) {
      gateSection += `\n\n${renderIssuesTable(gateNonSuggestions)}`;
    }
    if (gateSuggestion.length > 0) {
      gateSection += `\n\n${renderGroupedIssues(gateSuggestion, "Gate Suggestions")}`;
    }
  }

  const phaseSections = SCORING_PHASES.map((phase) =>
    renderPhaseDetail(phase, result.phases[phase]),
  ).join("\n\n");

  const goldenSection = result.phases.goldenSet
    ? `\n\n${renderGoldenSetDetail(result.phases.goldenSet)}`
    : "";

  return `
## Detailed Results

### Gate

${gateSection}

${phaseSections}${goldenSection}
`.trim();
}

function renderPhaseDetail(phase: string, phaseResult: PhaseResult): string {
  const phaseName = PHASE_NAMES[phase as keyof typeof PHASE_NAMES];

  const metricsSection =
    phaseResult.metrics && Object.keys(phaseResult.metrics).length > 0
      ? `**Metrics:**\n${Object.entries(phaseResult.metrics)
          .filter(([key]) => key !== "skipped" && key !== "reason")
          .map(([key, value]) => `- ${formatMetricName(key)}: ${value}`)
          .join("\n")}\n`
      : "";

  const explanationSection =
    phaseResult.explanation && phaseResult.score < 80
      ? `**Why this score:**\n${phaseResult.explanation.reasons.map((r) => `- ${r}`).join("\n")}\n\n` +
        (phaseResult.explanation.suggestions.length > 0
          ? `**Suggestions:**\n${phaseResult.explanation.suggestions.map((s) => `- ${s}`).join("\n")}\n`
          : "")
      : "";

  const issuesSection =
    phaseResult.issues.length > 0
      ? renderIssuesTable(phaseResult.issues)
      : phaseResult.metrics?.skipped
        ? ""
        : "✅ No issues found.";

  return `
### ${phaseName}

**Score:** ${phaseResult.score}/100

${metricsSection}
${explanationSection}
${issuesSection}
`.trim();
}

function renderGoldenSetDetail(phaseResult: PhaseResult): string {
  const m = phaseResult.metrics || {};
  const score = phaseResult.score;

  let categoryTable = "";
  if (m.categories) {
    try {
      const cats =
        typeof m.categories === "string"
          ? JSON.parse(m.categories)
          : m.categories;
      const catRows = Object.entries(
        cats as Record<string, Record<string, number>>,
      )
        .map(([cat, info]) => {
          const status =
            info.score >= 80 ? "✅" : info.score >= 50 ? "⚠️" : "❌";
          return `| ${cat} | ${info.passed}/${info.total} | ${info.score}/100 | ${info.weight}% | ${status} |`;
        })
        .join("\n");

      categoryTable = `
**Category Breakdown:**

| Category | Passed | Score | Weight | Status |
|----------|--------|-------|--------|--------|
${catRows}
`;
    } catch {
      // skip malformed categories
    }
  }

  const timingSection =
    m.avgResponseMs !== undefined
      ? `
**Response Time:**

| Metric | Value |
|--------|-------|
| Average | ${m.avgResponseMs}ms |
| P50 | ${m.p50ResponseMs ?? "-"}ms |
| P95 | ${m.p95ResponseMs ?? "-"}ms |
| Max | ${m.maxResponseMs ?? "-"}ms |
`
      : "";

  const contractSection =
    m.contractEndpoints !== undefined
      ? `
**Contract Tests (auto-generated from swagger.json):**

| Metric | Value |
|--------|-------|
| Endpoints tested | ${m.contractEndpoints} |
| Passed | ${m.contractPassed ?? "-"} |
| Failed | ${m.contractFailed ?? "-"} |
| Pass rate | ${m.contractPassRate ?? "-"}% |
| Avg response | ${m.contractAvgResponseMs ?? "-"}ms |
| Schema warnings | ${m.contractSchemaWarnings ?? 0} |
`
      : "";

  const scoreBreakdown =
    m.categoryScore !== undefined
      ? `
**Score Dimensions:**

| Dimension | Score | Weight |
|-----------|-------|--------|
| Category pass rate | ${m.categoryScore}/100 | 70% |
| Response time (P95) | ${m.responseTimeScore ?? "-"}/100 | 15% |
| Data consistency | ${m.consistencyScore ?? "-"}/100 | 15% |
`
      : "";

  const issuesSection =
    phaseResult.issues.length > 0
      ? renderIssuesTable(phaseResult.issues)
      : "✅ No issues found.";

  return `
### ${PHASE_NAMES.goldenSet}

**Score:** ${score}/100
**Features:** ${m.passedFeatures ?? 0}/${m.totalFeatures ?? 0} passed (${m.passRate ?? 0}%)

${scoreBreakdown}
${categoryTable}
${timingSection}
${contractSection}
${issuesSection}
`.trim();
}

function renderIssuesTable(issues: Issue[]): string {
  const sortedIssues = [...issues].sort((a, b) => {
    const order = { critical: 0, warning: 1, suggestion: 2 };
    return order[a.severity] - order[b.severity];
  });

  const rows = sortedIssues
    .map((issue) => {
      const severity = getSeverityEmoji(issue.severity);
      const location = issue.location
        ? `${path.basename(issue.location.file)}:${issue.location.line || "?"}`
        : "-";
      return `| ${severity} | ${issue.code} | ${issue.message} | ${location} |`;
    })
    .join("\n");

  return `
**Issues:**

| Severity | Code | Message | Location |
|----------|------|---------|----------|
${rows}
`.trim();
}

function renderReferenceInfo(result: ExtendedResult): string {
  const complexityIssues =
    result.reference.complexity.issues.length > 0
      ? renderComplexityTable(result.reference.complexity.issues)
      : "";

  return `
## Reference Info (no score impact)

These metrics are for reference only and do not affect the score.

### Complexity

- Total functions analyzed: ${result.reference.complexity.totalFunctions}
- Complex functions (>20): ${result.reference.complexity.complexFunctions}
- Max complexity: ${result.reference.complexity.maxComplexity}

${complexityIssues}

### Duplication

- Duplicate blocks: ${result.reference.duplication.totalBlocks}

### Naming

- Naming issues: ${result.reference.naming.totalIssues}

### JSDoc

- Missing JSDoc: ${result.reference.jsdoc.totalMissing}
`.trim();
}

function renderComplexityTable(issues: Issue[]): string {
  const displayIssues = issues.slice(0, MAX_DISPLAY_ISSUES);
  const rows = displayIssues
    .map((issue) => {
      const severity = getSeverityEmoji(issue.severity);
      const location = issue.location
        ? `${path.basename(issue.location.file)}:${issue.location.line || "?"}`
        : "-";
      return `| ${severity} | ${issue.code} | ${issue.message} | ${location} |`;
    })
    .join("\n");

  const moreRow =
    issues.length > MAX_DISPLAY_ISSUES
      ? `\n| ... | ... | *${issues.length - MAX_DISPLAY_ISSUES} more* | ... |`
      : "";

  return `
| Severity | Code | Message | Location |
|----------|------|---------|----------|
${rows}${moreRow}
`.trim();
}

function renderAgentEvaluations(agents?: AgentResult[]): string {
  if (!agents || agents.length === 0) return "";

  const agentSections = agents.map(renderAgentSection).join("\n\n");

  return `
## AI Agent Evaluations (${Math.round(AGENT_WEIGHT_RATIO * 100)}% of total score)

These evaluations are performed by AI agents and contribute 30% to the total score.

${agentSections}
`.trim();
}

function renderAgentSection(agent: AgentResult): string {
  const scoreEmoji = agent.score >= 80 ? "✅" : agent.score >= 60 ? "⚠️" : "❌";

  const tokensRow = agent.tokensUsed
    ? `| Tokens (in/out) | ${agent.tokensUsed.input} / ${agent.tokensUsed.output} |`
    : "";

  const issuesSection =
    agent.issues && agent.issues.length > 0
      ? renderAgentIssuesTable(agent.issues)
      : "✅ No issues found.";

  return `
### ${agent.agent}

**Score:** ${agent.score}/100 ${scoreEmoji}

| Property | Value |
|----------|-------|
| Provider | ${agent.provider} |
| Model | ${agent.model} |
| Duration | ${agent.durationMs}ms |
${tokensRow}

**Summary:** ${agent.summary}

${issuesSection}
`.trim();
}

function renderAgentIssuesTable(issues: AgentResult["issues"]): string {
  const displayIssues = issues.slice(0, 10);
  const rows = displayIssues
    .map((issue) => {
      const severity = getSeverityEmoji(issue.severity);
      const file = issue.file ? path.basename(issue.file) : "-";
      const desc =
        issue.description.length > 60
          ? issue.description.substring(0, 60) + "..."
          : issue.description;
      return `| ${severity} | ${issue.type} | ${desc} | ${file} |`;
    })
    .join("\n");

  const moreRow =
    issues.length > 10
      ? `\n| ... | ... | *${issues.length - 10} more issues* | ... |`
      : "";

  return `
**Issues Found:**

| Severity | Type | Description | File |
|----------|------|-------------|------|
${rows}${moreRow}
`.trim();
}

function renderSummary(result: ExtendedResult): string {
  let penaltyRows = "";
  if (result.penalties) {
    if (result.penalties.warning) {
      penaltyRows += `| Warning Penalty | -${result.penalties.warning.amount} (${result.penalties.warning.ratio}) |\n`;
    }
    if (result.penalties.duplication) {
      penaltyRows += `| Duplication Penalty | -${result.penalties.duplication.amount} (${result.penalties.duplication.blocks} blocks) |\n`;
    }
    if (result.penalties.jsdoc) {
      penaltyRows += `| JSDoc Penalty | -${result.penalties.jsdoc.amount} (${result.penalties.jsdoc.missing} missing, ${result.penalties.jsdoc.ratio}) |\n`;
    }
    if (result.penalties.schemaSync) {
      penaltyRows += `| Schema Sync Penalty | -${result.penalties.schemaSync.amount} (${result.penalties.schemaSync.emptyTypes} empty types, ${result.penalties.schemaSync.mismatchedProperties} mismatched) |\n`;
    }
    if (result.penalties.suggestionOverflow) {
      penaltyRows += `| Suggestion Overflow | -${result.penalties.suggestionOverflow.amount} (${result.penalties.suggestionOverflow.count} suggestions) |\n`;
    }
  }

  const criticalDetail =
    result.criticalIssues.length > 0
      ? `\n${renderGroupedIssues(result.criticalIssues, "Critical Issues")}`
      : "";

  const warningDetail =
    result.warnings.length > 0
      ? `\n${renderGroupedIssues(result.warnings, "Warnings")}`
      : "";

  const suggestionDetail =
    result.suggestions.length > 0
      ? `\n${renderGroupedIssues(result.suggestions, "Suggestions")}`
      : "";

  return `
## Summary

| Category | Count |
|----------|-------|
| Total Issues (scoring) | ${result.summary.totalIssues} |
| Critical | ${result.summary.criticalCount} |
| Warnings | ${result.summary.warningCount} |
| Suggestions | ${result.summary.suggestionCount} |
${penaltyRows}
${criticalDetail}
${warningDetail}
${suggestionDetail}
`.trim();
}

/** Group issues by code and render as a markdown table (top N) */
function renderGroupedIssues(
  issues: Issue[],
  title: string,
  maxRows: number = 10,
): string {
  const grouped = new Map<
    string,
    { message: string; severity: string; count: number; files: string[] }
  >();

  for (const issue of issues) {
    const existing = grouped.get(issue.code);
    const file = issue.location
      ? `${path.basename(issue.location.file)}:${issue.location.line || "?"}`
      : "-";

    if (existing) {
      existing.count++;
      if (!existing.files.includes(file) && existing.files.length < 3) {
        existing.files.push(file);
      }
    } else {
      grouped.set(issue.code, {
        message: issue.message,
        severity: issue.severity,
        count: 1,
        files: [file],
      });
    }
  }

  const sorted = [...grouped.entries()].sort((a, b) => b[1].count - a[1].count);
  const display = sorted.slice(0, maxRows);

  const rows = display
    .map(([code, info]) => {
      const severity = getSeverityEmoji(info.severity);
      const files = info.files.join(", ");
      return `| ${severity} | ${code} | ${info.count} | ${info.message} | ${files} |`;
    })
    .join("\n");

  const moreRow =
    sorted.length > maxRows
      ? `\n| ... | ... | ... | *${sorted.length - maxRows} more issue types* | ... |`
      : "";

  return `
### ${title} (${issues.length} total)

| Severity | Code | Count | Message | Example Locations |
|----------|------|-------|---------|-------------------|
${rows}${moreRow}
`.trim();
}

function getStatusEmoji(score: number, skipped?: boolean): string {
  if (skipped) return "⏭️ Skipped";
  if (score >= 90) return "✅ Excellent";
  if (score >= 80) return "👍 Good";
  if (score >= 70) return "📊 Average";
  if (score >= 50) return "⚠️ Below Average";
  return "❌ Poor";
}

function getSeverityEmoji(severity: string): string {
  switch (severity) {
    case "critical":
      return "🔴 Critical";
    case "warning":
      return "🟡 Warning";
    case "suggestion":
      return "🔵 Suggestion";
    default:
      return severity;
  }
}

function formatMetricName(key: string): string {
  return key
    .replace(/([A-Z])/g, " $1")
    .replace(/^./, (str) => str.toUpperCase())
    .trim();
}
