import { tags } from "typia";

import { AutoBeAgentHistoryBase } from "./AutoBeHistoryBase";
import { AutoBeProcessAggregateCollection } from "./contents/AutoBeProcessAggregateCollection";

/**
 * History record generated by the Describe agent after converting images to
 * planning documents.
 *
 * This history captures the results of the describe phase where user-provided
 * images such as UI mockups, wireframes, screenshots, or diagrams are analyzed
 * and transformed into comprehensive planning documents. The Describe agent is
 * responsible for interpreting visual elements and extracting backend
 * requirements from them, converting implicit visual information into explicit
 * textual specifications.
 *
 * The describe phase bridges the gap between visual design and technical
 * implementation by analyzing UI components, user interactions, data flows, and
 * business logic implied by the images. It generates detailed planning
 * documents that specify API endpoints, data models, validation rules, and
 * business logic that would be needed to support the functionality shown in the
 * visual mockups.
 *
 * This history is crucial for traceability, allowing developers to understand
 * how visual requirements were interpreted and what planning decisions were
 * made based on the provided images. It serves as the foundation for all
 * subsequent phases in the AutoBE pipeline.
 *
 * @author michael
 */
export interface AutoBeDescribeHistory
  extends AutoBeAgentHistoryBase<"describe"> {
  /**
   * The complete B2B SaaS requirements document.
   *
   * A comprehensive specification document that combines all integrated
   * sections into a cohesive whole, following enterprise software documentation
   * standards. Written entirely in English, this document serves as the
   * foundation for backend application development.
   */
  document: string;

  /**
   * Executive summary of the complete system.
   *
   * Provides a high-level overview of all functional areas, key features, and
   * the overall system architecture derived from image analysis.
   */
  summary: string;

  /**
   * List of all functional areas covered in the document.
   *
   * Each entry corresponds to a major section in the final document, helping
   * readers navigate to specific areas of interest.
   */
  sections: string[];

  aggregates: AutoBeProcessAggregateCollection<"describe">;

  /**
   * Iteration step of the describe phase.
   *
   * Indicates the current iteration of image analysis and document generation.
   * A value of 0 indicates the initial analysis, while higher values represent
   * subsequent iterations that may have been triggered by additional images or
   * refinements to the planning document.
   */
  step: number;

  /**
   * ISO 8601 timestamp indicating when the describe process was completed.
   *
   * Marks the exact moment when the Describe agent finished analyzing all
   * provided images and generating the comprehensive planning document. This
   * timestamp is crucial for tracking the development timeline and
   * understanding when the visual requirements were transformed into textual
   * specifications.
   */
  completed_at: string & tags.Format<"date-time">;
}
