import { tags } from "typia";

import { AutoBeAgentHistoryBase } from "./AutoBeHistoryBase";
import { AutoBeProcessAggregateCollection } from "./contents/AutoBeProcessAggregateCollection";
import { AutoBeUserMessageContent } from "./contents/AutoBeUserMessageContent";

/**
 * History record generated by the Describe agent after converting images to
 * planning documents.
 *
 * This history captures the results of the describe phase where user-provided
 * images such as UI mockups, wireframes, screenshots, or diagrams are analyzed
 * and transformed into comprehensive planning documents. The Describe agent is
 * responsible for interpreting visual elements and extracting backend
 * requirements from them, converting implicit visual information into explicit
 * textual specifications.
 *
 * The describe phase bridges the gap between visual design and technical
 * implementation by analyzing UI components, user interactions, data flows, and
 * business logic implied by the images. It generates detailed planning
 * documents that specify API endpoints, data models, validation rules, and
 * business logic that would be needed to support the functionality shown in the
 * visual mockups.
 *
 * This history is crucial for traceability, allowing developers to understand
 * how visual requirements were interpreted and what planning decisions were
 * made based on the provided images. It serves as the foundation for all
 * subsequent phases in the AutoBE pipeline.
 *
 * @author michael
 */
export interface AutoBeDescribeHistory
  extends AutoBeAgentHistoryBase<"describe"> {
  /**
   * The transformed content ready to be passed to the facade agent.
   *
   * This array contains the processed user message content where image
   * attachments have been analyzed and converted into detailed planning
   * documents. Each content item represents either the original text messages
   * from the user or the generated planning documents that describe backend
   * requirements extracted from images.
   *
   * The planning documents include comprehensive specifications for:
   *
   * - API endpoints inferred from UI interactions
   * - Data models based on displayed information
   * - Business logic implied by user flows
   * - Validation rules derived from form inputs
   * - Authentication and authorization requirements
   * - File upload/download functionality
   * - Real-time features if indicated in the UI
   *
   * These contents serve as the primary input for the facade agent to begin the
   * backend application generation process.
   */
  contents: AutoBeUserMessageContent[];

  aggregates: AutoBeProcessAggregateCollection<"describe">;

  /**
   * Iteration number of the requirements analysis report this API design was
   * performed for.
   *
   * Indicates which version of the requirements analysis this API design
   * reflects. If this value is lower than {@link AutoBeAnalyzeHistory.step}, it
   * means the API design has not yet been updated to reflect the latest
   * requirements and may need to be regenerated.
   *
   * A value of 0 indicates the initial API design, while higher values
   * represent subsequent revisions based on updated requirements or database
   * schema changes.
   */
  step: number;

  /**
   * ISO 8601 timestamp indicating when the API design process was completed.
   *
   * Marks the exact moment when the Interface agent finished the complete
   * transformation pipeline from AST construction through OpenAPI validation to
   * NestJS code generation. This timestamp is crucial for tracking the
   * development timeline and determining the currency of the API design
   * relative to other development artifacts.
   */
  completed_at: string & tags.Format<"date-time">;
}
