import { AutoBeOpenApi } from "@autobe/interface";
import { StringUtil } from "@autobe/utils";
import { v7 } from "uuid";

import { AutoBeSystemPromptConstant } from "../../../constants/AutoBeSystemPromptConstant";
import { IAutoBeOrchestrateHistory } from "../../../structures/IAutoBeOrchestrateHistory";
import { AutoBePreliminaryController } from "../../common/AutoBePreliminaryController";

export const transformInterfaceSchemaHistory = (props: {
  operations: AutoBeOpenApi.IOperation[];
  typeName: string;
  otherTypeNames: string[];
  preliminary: AutoBePreliminaryController<
    | "analysisFiles"
    | "databaseSchemas"
    | "interfaceOperations"
    | "previousAnalysisFiles"
    | "previousDatabaseSchemas"
    | "previousInterfaceOperations"
    | "previousInterfaceSchemas"
  >;
  instruction: string;
}): IAutoBeOrchestrateHistory => {
  return {
    histories: [
      {
        type: "systemMessage",
        id: v7(),
        created_at: new Date().toISOString(),
        text: AutoBeSystemPromptConstant.INTERFACE_SCHEMA,
      },
      ...props.preliminary.getHistories(),
      {
        type: "assistantMessage",
        id: v7(),
        created_at: new Date().toISOString(),
        text: StringUtil.trim`
          ## API Design Instructions

          The following API-specific instructions were extracted from
          the user's requirements. These focus on API interface design aspects
          such as endpoint patterns, request/response formats, DTO schemas,
          and operation specifications.

          Follow these instructions when creating JSON schema.

          Carefully distinguish between:
          
          - Suggestions or recommendations (consider these as guidance)
          - Direct specifications or explicit commands (these must be followed exactly)

          When instructions contain direct specifications or explicit design decisions,
          follow them precisely even if you believe you have better alternatives.

          ${props.instruction}

          ## Operations (Filtered for Target Schemas)

          Here is the list of API operations that directly use the schemas
          you need to generate (via requestBody.typeName or responseBody.typeName).

          These are the ONLY operations relevant to your current task - other
          operations have been filtered out to reduce noise and improve focus:

          \`\`\`json
          ${JSON.stringify(props.operations)}
          \`\`\`

          ## Other DTO Type names you can reference

          While creating the JSON schema for the target type, you can reference
          other DTO types defined in the API. Here are their type names:

          - ${props.otherTypeNames.map((name) => `- ${name}`).join("\n")}

          ## DTO type to create
          
          Here is the specific type you need to create a JSON schema component for.
          
          - ${JSON.stringify(props.typeName)}
        `,
      },
    ],
    userMessage: StringUtil.trim`
      Make ${JSON.stringify(props.typeName)} type named JSON schema component
      based on the provided API design instructions and relevant operations.

      Note that, not making "Record<string, AutoBeOpenApi.IJsonSchemaDescriptive>"
      type, but making "AutoBeOpenApi.IJsonSchemaDescriptive" type directly for
      the ${JSON.stringify(props.typeName)} type.

      ## CRITICAL: Object Type Property Construction Rules

      When designing schemas, prefer object types whenever semantically appropriate.

      For ALL object type schemas, you MUST follow these ABSOLUTE rules:

      **1. MANDATORY Property Field Order:**
      Every property MUST be constructed in this exact order:
      \`\`\`
      1. x-autobe-database-schema-property  →  WHERE does data come from?
      2. x-autobe-specification           →  HOW to implement/compute?
      3. description                      →  WHAT for API consumers?
      4. Type metadata (type, format...)  →  WHAT technically?
      \`\`\`

      **2. NEVER Omit Required Fields:**
      - \`x-autobe-database-schema-property\`: MANDATORY on every property (string property name or null)
      - \`x-autobe-specification\`: MANDATORY on every property (implementation details)
      - Omitting these fields is a CRITICAL ERROR that will cause validation failure

      **3. Example - Correct Property Structure:**
      \`\`\`json
      {
        "email": {
          "x-autobe-database-schema-property": "email",
          "x-autobe-specification": "Direct mapping from users.email column.",
          "description": "User's email address for login.",
          "type": "string",
          "format": "email"
        }
      }
      \`\`\`

      ## ABSOLUTE: Validation Feedback Compliance

      Validation feedback is generated by deterministic code logic, NOT by AI judgment.
      Its reliability is 100% guaranteed.

      **You MUST:**
      - Absolutely obey ALL validation feedback without exception
      - Treat validation errors as facts, not suggestions
      - Fix every reported issue exactly as indicated

      **You MUST NEVER:**
      - Prioritize your own judgment over validation feedback
      - Ignore or dismiss validation feedback for any reason
      - Assume validation feedback is incorrect
      - Override validation feedback based on your own analysis

      If validation feedback indicates an error, that error EXISTS. Fix it.
    `,
  };
};
