import { AutoBeOpenApi } from "@autobe/interface";
import { StringUtil } from "@autobe/utils";
import { v7 } from "uuid";

import { AutoBeSystemPromptConstant } from "../../../constants/AutoBeSystemPromptConstant";
import { IAutoBeOrchestrateHistory } from "../../../structures/IAutoBeOrchestrateHistory";
import { AutoBePreliminaryController } from "../../common/AutoBePreliminaryController";
import { IAutoBeInterfaceBaseEndpointApplication } from "../structures/IAutoBeInterfaceBaseEndpointApplication";

export const transformInterfaceBaseEndpointReviewHistory = (props: {
  preliminary: AutoBePreliminaryController<"analysisFiles" | "prismaSchemas">;
  endpoints: IAutoBeInterfaceBaseEndpointApplication.IEndpoint[];
  authorizations: AutoBeOpenApi.IOperation[];
}): IAutoBeOrchestrateHistory => {
  return {
    histories: [
      {
        type: "systemMessage",
        id: v7(),
        created_at: new Date().toISOString(),
        text: AutoBeSystemPromptConstant.INTERFACE_BASE_ENDPOINT,
      },
      {
        type: "systemMessage",
        id: v7(),
        created_at: new Date().toISOString(),
        text: AutoBeSystemPromptConstant.INTERFACE_BASE_ENDPOINT_REVIEW,
      },
      ...props.preliminary.getHistories(),
      {
        id: v7(),
        type: "assistantMessage",
        text: StringUtil.trim`
        ## Base CRUD Endpoints for Review

        Below are the base CRUD endpoints generated by the Base Endpoint Generator.
        Review each endpoint for:

        1. **🚨 Plural/Singular (FIRST PRIORITY)**: Scan resource collection names for singular forms → UPDATE to plural. Check for duplicate pairs (both singular and plural versions).
        2. **Semantic Duplicates**: Compare descriptions of similar paths → DELETE redundant ones.
        3. **Naming**: Does the path follow hierarchical \`/\` structure? No camelCase concatenation.
        4. **Necessity**: Is this endpoint required by the service? Check against requirements.
        5. **Stance Rules**: Subsidiary entities must be nested under parent. Snapshot entities are read-only.
        6. **Composite Unique**: Entities with \`@@unique([parent_id, code])\` must use nested paths only.

        \`\`\`json
        ${JSON.stringify(props.endpoints, null, 2)}
        \`\`\`

        ## Authorization Endpoints (Already Exist)

        These authorization endpoints already exist. Do NOT create duplicates:

        \`\`\`json
        ${JSON.stringify(
          props.authorizations.map((op) => ({
            path: op.path,
            method: op.method,
          })),
          null,
          2,
        )}
        \`\`\`

        ## How to Complete

        Call \`process()\` with \`type: "complete"\` containing all \`actions\` (create/update/delete) at once.
      `,
        created_at: new Date().toISOString(),
      },
    ],
    userMessage: "Review the base CRUD endpoints and fix any issues found.",
  };
};
