import { AutoBeOpenApi } from "@autobe/interface";
import { StringUtil } from "@autobe/utils";
import { v7 } from "uuid";

import { AutoBeSystemPromptConstant } from "../../../constants/AutoBeSystemPromptConstant";
import { IAutoBeOrchestrateHistory } from "../../../structures/IAutoBeOrchestrateHistory";
import { AutoBePreliminaryController } from "../../common/AutoBePreliminaryController";
import { IAutoBeInterfaceActionEndpointApplication } from "../structures/IAutoBeInterfaceActionEndpointApplication";

export const transformInterfaceActionEndpointReviewHistory = (props: {
  preliminary: AutoBePreliminaryController<"analysisFiles" | "prismaSchemas">;
  endpoints: IAutoBeInterfaceActionEndpointApplication.IEndpoint[];
  baseEndpoints: AutoBeOpenApi.IEndpoint[];
  authorizations: AutoBeOpenApi.IOperation[];
}): IAutoBeOrchestrateHistory => ({
  histories: [
    {
      type: "systemMessage",
      id: v7(),
      created_at: new Date().toISOString(),
      text: AutoBeSystemPromptConstant.INTERFACE_ACTION_ENDPOINT,
    },
    {
      type: "systemMessage",
      id: v7(),
      created_at: new Date().toISOString(),
      text: AutoBeSystemPromptConstant.INTERFACE_ACTION_ENDPOINT_REVIEW,
    },
    ...props.preliminary.getHistories(),
    {
      id: v7(),
      type: "assistantMessage",
      text: StringUtil.trim`
        ## Action Endpoints for Review

        Below are the action (non-CRUD) endpoints generated by the Action Endpoint Generator.
        These endpoints provide analytics, dashboards, search, reports, and enriched data views.

        Review each endpoint for:

        1. **🚨 Plural/Singular (FIRST PRIORITY)**: Scan resource collection names for singular forms → UPDATE to plural. Check for duplicate pairs (both singular and plural versions).
        2. **Semantic Duplicates**: Compare descriptions of similar paths → DELETE redundant ones. Check overlap with base CRUD functionality.
        3. **Naming**: Does the path follow hierarchical \`/\` structure? No camelCase concatenation.
           - \`/statistics/sales/monthly\` ✅
           - \`/statistics/salesByMonth\` ❌
        4. **Requirements Justification**: Is this endpoint justified by requirements? Look for keywords like "analytics", "dashboard", "search", "report", "overview", "metrics".
        5. **HTTP Method**: GET for simple queries, PATCH for complex filtering.

        \`\`\`json
        ${JSON.stringify(props.endpoints, null, 2)}
        \`\`\`

        ## Base CRUD Endpoints (Already Exist)

        These base CRUD endpoints already exist. Action endpoints should COMPLEMENT, not duplicate:

        \`\`\`json
        ${JSON.stringify(props.baseEndpoints, null, 2)}
        \`\`\`

        ## Authorization Endpoints (Already Exist)

        These authorization endpoints already exist. Do NOT create duplicates:

        \`\`\`json
        ${JSON.stringify(
          props.authorizations.map((op) => ({
            path: op.path,
            method: op.method,
          })),
          null,
          2,
        )}
        \`\`\`

        ## How to Complete

        Call \`process()\` with \`type: "complete"\` containing all \`actions\` (create/update/delete) at once.
      `,
      created_at: new Date().toISOString(),
    },
  ],
  userMessage: "Review the action endpoints and fix any issues found.",
});
