import { AutoBeOpenApi } from "@autobe/interface";
import { v7 } from "uuid";

import { AutoBeSystemPromptConstant } from "../../../constants/AutoBeSystemPromptConstant";
import { AutoBeState } from "../../../context/AutoBeState";
import { IAutoBeOrchestrateHistory } from "../../../structures/IAutoBeOrchestrateHistory";
import { transformInterfaceAssetHistories } from "./transformInterfaceAssetHistories";

export const transformInterfaceEndpointsReviewHistories = (
  state: AutoBeState,
  endpoints: AutoBeOpenApi.IEndpoint[],
): IAutoBeOrchestrateHistory => ({
  histories: [
    {
      type: "systemMessage",
      id: v7(),
      created_at: new Date().toISOString(),
      text: AutoBeSystemPromptConstant.INTERFACE_ENDPOINT,
    },
    ...transformInterfaceAssetHistories(state),
    {
      id: v7(),
      type: "assistantMessage",
      text: [
        "Below are endpoints generated by your request.",
        "",
        "```json",
        JSON.stringify(endpoints),
        "```",
      ].join("\n"),
      created_at: new Date().toISOString(),
    },
    {
      id: v7(),
      type: "systemMessage",
      text: AutoBeSystemPromptConstant.INTERFACE_ENDPOINTS_REVIEW,
      created_at: new Date().toISOString(),
    },
  ],
  userMessage: "Review the generated endpoints please",
});
