import { BaseAgent } from './base-agent';
import { AgentConfig, AgentResult } from './types';
import { EvaluationContext } from '../types';
import * as path from 'path';
import * as fs from 'fs/promises';

/**
 * LLM Quality evaluation agent
 */
export class LLMQualityAgent extends BaseAgent {
  readonly name = 'LLMQualityAgent';
  readonly description = 'Evaluates AI-generated code for common LLM mistakes';

  constructor(config: AgentConfig) {
    super(config);
  }

  async evaluate(context: EvaluationContext): Promise<AgentResult> {
    const startTime = performance.now();

    const targetFiles = context.files.providers;

    if (targetFiles.length === 0) {
      return {
        agent: this.name,
        provider: this.config.provider,
        model: this.client.getModel(),
        issues: [],
        score: 100,
        summary: 'No files to evaluate',
        durationMs: Math.round(performance.now() - startTime),
      };
    }

    let requirementsContent = '';
    if (context.project.analysisDir) {
      try {
        const files = await fs.readdir(context.project.analysisDir);
        for (const file of files.slice(0, 5)) {
          if (file.endsWith('.md')) {
            const content = await fs.readFile(
              path.join(context.project.analysisDir, file),
              'utf-8'
            );
            requirementsContent += `\n### ${file}\n${content}\n`;
          }
        }
      } catch (error) {
        console.error('Failed to read requirements:', error);
      }
    }

    const fileContents = await this.readFiles(targetFiles);

    let codeContent = '';
    for (const [filePath, content] of fileContents) {
      const relativePath = path.relative(context.project.rootPath, filePath);
      codeContent += `\n### File: ${relativePath}\n\`\`\`typescript\n${content}\n\`\`\`\n`;
    }

    requirementsContent = this.truncateContent(requirementsContent, 20000);
    codeContent = this.truncateContent(codeContent, 30000);

    const systemPrompt = `You are a code reviewer specializing in AI-generated code.
This code was generated by AutoBE (an AI backend code generator).

Find common LLM mistakes:
1. Hallucinations - Non-existent libraries/APIs
2. Incomplete Implementation - Stubs or "not implemented"
3. Logic Errors - Code doesn't match requirements
4. Copy-Paste Errors - Duplicate code with inconsistent changes
5. Placeholder Code - TODOs, hardcoded values
6. Unrealistic Assumptions
7. Missing Edge Cases
8. Inconsistent Naming
9. Dead Code
10. Requirements Mismatch

Respond ONLY with valid JSON:
{
  "issues": [
    {
      "severity": "critical|warning|suggestion",
      "type": "hallucination|incomplete|logic-error|copy-paste|placeholder|assumption|edge-case|naming|dead-code|requirements-mismatch",
      "file": "relative/path/to/file.ts",
      "line": 42,
      "description": "Clear description",
      "suggestion": "How to fix"
    }
  ],
  "score": 85,
  "summary": "Brief assessment"
}`;

    let userPrompt = `Analyze this AI-generated code:\n`;
    if (requirementsContent) {
      userPrompt += `\n## Requirements\n${requirementsContent}\n`;
    }
    userPrompt += `\n## Code\n${codeContent}\n\nRespond ONLY with valid JSON.`;

    try {
      const response = await this.client.chat(systemPrompt, userPrompt);
      const parsed = this.parseResponse(response.content);

      return {
        agent: this.name,
        provider: this.config.provider,
        model: this.client.getModel(),
        issues: parsed.issues,
        score: parsed.score,
        summary: parsed.summary,
        durationMs: Math.round(performance.now() - startTime),
        tokensUsed: response.tokensUsed,
      };
    } catch (error) {
      console.error('LLMQualityAgent error:', error);
      return {
        agent: this.name,
        provider: this.config.provider,
        model: this.client.getModel(),
        issues: [],
        score: 100,
        summary: `Error: ${error instanceof Error ? error.message : 'Unknown error'}`,
        durationMs: Math.round(performance.now() - startTime),
      };
    }
  }
}
