import { AutoBeAnalyzeFile } from "../histories/contents/AutoBeAnalyzeFile";
import { AutoBeEventBase } from "./AutoBeEventBase";

/**
 * Event fired during the review and amendment phase of the requirements
 * analysis process.
 *
 * This event represents the quality assurance activity of the Analyze Review Agent,
 * which validates documents produced by the Analyze Writer Agent. The reviewer
 * ensures that requirements documentation meets AutoBE's strict standards before
 * proceeding to the development phases.
 *
 * The Analyze Review Agent performs comprehensive validation including:
 * - Document length verification (minimum 2,000 characters, excluding TOC)
 * - Table of contents completeness check (all sections must be filled)
 * - Internal anchor link validation (all #links must be valid)
 * - Mermaid diagram syntax verification (especially quote usage rules)
 * - EARS format compliance for functional requirements
 *
 * Review outcomes:
 * - **Accept**: Document meets all criteria and can proceed to next phase
 * - **Reject**: Document requires revision with specific feedback provided
 *
 * Key characteristics of the review process:
 * - Reviewer provides only feedback and commands, never writes content directly
 * - Reviews one document at a time with focused attention
 * - Enforces strict Mermaid syntax rules (no parentheses within brackets)
 * - Iterative process continues until document meets all quality standards
 *
 * The review ensures that subsequent agents (Prisma, Interface, Test, Realize)
 * receive well-structured, unambiguous requirements that enable fully automated
 * backend development without human intervention.
 *
 * For detailed information about the Analyze Review Agent's validation rules
 * and criteria, refer to packages/agent/prompts/ANALYZE_REVIEW.md
 *
 * @author Kakasoo
 */
export interface AutoBeAnalyzeReviewEvent
  extends AutoBeEventBase<"analyzeReview"> {
  /**
   * Original file content submitted for review.
   * 
   * Contains the markdown document generated by the Analyze Writer Agent,
   * including all sections such as business model, functional requirements,
   * API specifications, and ERD diagrams that need validation.
   */
  file: AutoBeAnalyzeFile;

  /**
   * Detailed review feedback from the Analyze Review Agent.
   * 
   * Contains specific validation results including:
   * - Document length assessment
   * - Missing or incomplete sections
   * - Invalid anchor links
   * - Mermaid syntax errors
   * - EARS format violations
   * - Overall quality assessment and recommendations
   */
  review: string;

  /**
   * Amendment plan based on the review feedback.
   * 
   * Outlines specific changes to be made to address review comments.
   * If the original document is perfect and requires no modifications,
   * this field will explicitly state that no changes are needed.
   * 
   * The plan serves as a bridge between review feedback and actual
   * document revision, ensuring all identified issues are addressed.
   */
  plan: string;

  /**
   * Revised content based on the amendment plan.
   * 
   * Contains the fully updated markdown document incorporating all
   * review feedback. If the original document was perfect and required
   * no changes, this will be identical to the original content.
   * 
   * This revised content must pass all validation criteria before
   * the document can proceed to the next development phase.
   */
  content: string;

  /**
   * Current iteration number of the requirements analysis being reviewed.
   *
   * Indicates which version of the requirements analysis is undergoing review
   * and amendment. This step number helps track the iterative refinement
   * process and provides context for understanding how many revision cycles
   * have been completed.
   *
   * The step value increments with each major revision cycle, allowing
   * stakeholders to understand the evolution of the requirements and the level
   * of refinement that has been applied to achieve the final analysis.
   */
  step: number;

  /**
   * Total number of documents to review in the current session.
   * 
   * Represents the complete set of requirement documents that need
   * validation. Complex projects may have multiple documents requiring
   * individual review cycles.
   */
  total: number;

  /**
   * Number of documents reviewed and finalized so far.
   * 
   * Tracks progress through the review process when multiple requirement
   * documents need validation. Each document must pass review before
   * the count increments.
   */
  completed: number;
}
