import { AutoBeOpenApi } from "../openapi";
import { AutoBeEventBase } from "./AutoBeEventBase";
import { AutoBeTokenUsageEventBase } from "./AutoBeTokenUsageEventBase";

/**
 * Event fired during the review and validation phase of API endpoint
 * definitions.
 *
 * This event occurs when the Interface agent is reviewing and validating the
 * generated API endpoints against business requirements, technical
 * specifications, and REST API design principles. The review phase ensures that
 * each endpoint properly follows RESTful conventions with correct paths, HTTP
 * methods, and adherence to API design best practices.
 *
 * The review process involves systematic validation where the agent evaluates
 * endpoint naming consistency, path structure correctness, HTTP method
 * appropriateness, and overall API design patterns. Endpoints that fail
 * validation are marked for revision to ensure the final API specification
 * maintains consistent and intuitive REST API structure.
 *
 * @author Kakasoo
 */
export interface AutoBeInterfaceEndpointsReviewEvent
  extends AutoBeEventBase<"interfaceEndpointsReview">,
    AutoBeTokenUsageEventBase {
  /**
   * Original API endpoints submitted for review.
   *
   * The complete set of endpoints generated by the Interface Endpoints Agent
   * that require validation for RESTful compliance, naming consistency, path
   * structure correctness, and adherence to AutoBE standards. These are the
   * endpoints being evaluated for potential issues and improvements.
   */
  endpoints: AutoBeOpenApi.IEndpoint[];

  /**
   * Detailed review feedback from the Interface Endpoints Review Agent.
   *
   * Contains comprehensive assessment results including:
   *
   * - RESTful convention compliance
   * - Path structure validation
   * - HTTP method appropriateness
   * - Naming consistency verification
   * - Identified design issues and recommendations
   */
  review: string;

  /**
   * Revised endpoints based on the amendment plan.
   *
   * The final corrected API endpoints after applying all fixes from the
   * improvement plan. If no issues were found during review, this contains the
   * original endpoints unchanged. These enhanced endpoints are ready for
   * operation generation and subsequent implementation phases.
   */
  content: AutoBeOpenApi.IEndpoint[];

  /**
   * Current iteration number of the endpoint review process.
   *
   * Indicates which revision cycle of the API endpoint review is currently
   * being executed. This step number helps track the iterative validation
   * process and provides context for understanding how many review cycles have
   * been completed to achieve the desired endpoint quality.
   *
   * The step value increments with each major review iteration, allowing
   * stakeholders to monitor the progressive refinement of API endpoints and
   * understand the validation rigor applied to the interface design.
   */
  step: number;
}
