import { AutoBeEventBase } from "./AutoBeEventBase";

/**
 * Event fired when the AutoAPI Schema Review Agent validates individual schema
 * definitions.
 *
 * This event occurs during the thorough review process where the AutoAPI Schema
 * Review Agent evaluates each schema generated by the AutoAPI Schema Agent
 * against strict compliance rules. The review ensures that schemas fully comply
 * with OpenAPI standards, security requirements, naming conventions, and
 * completeness criteria as defined in the AutoAPI Schema Agent System Prompt.
 *
 * The review process validates that all entities from the Prisma schema and API
 * operations are properly defined, sensitive information is appropriately
 * handled, and the schema structure maintains consistency across all type
 * definitions. Each schema undergoes individual scrutiny to ensure
 * enterprise-level quality and production readiness.
 *
 * @author Kakasoo
 */
export interface AutoBeInterfaceSchemasReviewEvent
  extends AutoBeEventBase<"interfaceSchemasReview"> {
  /**
   * Name of the specific schema being reviewed.
   *
   * This is the exact schema name from the review target list that the AutoAPI
   * Schema Review Agent is currently evaluating. The name must match one of the
   * predefined target schemas and corresponds to a named type definition in the
   * OpenAPI specification's components/schemas section.
   */
  schema: string;

  /**
   * Detailed review feedback for the specific schema.
   *
   * Contains the AutoAPI Schema Review Agent's comprehensive evaluation results
   * following the core review checklist. The review validates multiple
   * dimensions including output format compliance, entity coverage, property
   * definitions, security requirements, and consistency.
   *
   * **Review Checklist:**
   *
   * - **Output Format**: Validates use of named types with `$ref`, prohibits
   *   inline/anonymous object definitions
   * - **Entity Coverage**: Ensures all Prisma entities and API operation entities
   *   are defined with necessary derived types (`.ICreate`, `.IUpdate`,
   *   `.ISummary`, `.IRequest`)
   * - **Property Definitions**: Verifies all Prisma properties are included, type
   *   mapping follows Prisma → OpenAPI conversion, required/optional fields
   *   match constraints, and each property has detailed English descriptions
   * - **Security Requirements**: Confirms sensitive fields (passwords, tokens,
   *   API keys) are removed from response types, request types don't accept
   *   actor IDs directly, and ownership transfer fields are excluded from
   *   update types
   * - **Consistency**: Validates naming conventions (`IEntityName`,
   *   `IEntityName.ICreate`), relationship definitions via `$ref`, and standard
   *   pagination structure (`IPage`)
   *
   * **Review Format:**
   *
   * Each checklist item is marked as "✅ Pass" or "❌ Issue" with detailed
   * problem descriptions, concrete examples, and specific fix suggestions for
   * any failures. The review includes an overall quality assessment and
   * prioritized improvement list.
   *
   * **Example:**
   *
   *     "[Review Results]
   *     1. Output Format
   *     - ✅ Uses schemas record format
   *     - ✅ All objects defined as named types with $ref
   *
   *     2. Entity Coverage
   *     - ✅ All Prisma entities included
   *     - ✅ All API operation entities defined
   *
   *     3. Property Definitions
   *     - ✅ All properties from Prisma schema present
   *     - ✅ Type mapping correctly follows conversion rules
   *     - ✅ Required/optional fields match Prisma constraints
   *
   *     4. Security Requirements
   *     - ✅ No sensitive fields in response types
   *     - ✅ Request types don't accept actor IDs
   *
   *     5. Consistency
   *     - ✅ Naming convention followed
   *     - ✅ Relationships properly use $ref
   *
   *     [Overall Assessment]
   *     Schema passes all validation checks and is production-ready."
   */
  review: string;

  /**
   * Current iteration step of the schema review process.
   *
   * Indicates the review cycle number for tracking iterative validation and
   * refinement. The step increments with each review iteration as schemas are
   * progressively improved based on feedback until they meet all compliance
   * requirements.
   */
  step: number;

  /**
   * Total number of API schemas to be reviewed and validated.
   *
   * Represents the complete count of schemas that need to undergo the review
   * process. This includes all endpoints across different API paths and HTTP
   * methods that were generated based on the requirements analysis and need
   * validation against business logic and technical specifications.
   */
  total: number;

  /**
   * Number of API schemas that have successfully passed review validation.
   *
   * Contains the count of schemas that have been reviewed and approved as
   * meeting all quality criteria including correct request/response schemas,
   * proper authentication handling, comprehensive error responses, and complete
   * documentation. These schemas are ready for implementation.
   */
  completed: number;
}
