import { AutoBeOpenApi } from "../openapi";
import { AutoBeAggregateEventBase } from "./base/AutoBeAggregateEventBase";
import { AutoBeEventBase } from "./base/AutoBeEventBase";
import { AutoBeProgressEventBase } from "./base/AutoBeProgressEventBase";

/**
 * Event fired during the review and validation phase of a single API operation.
 *
 * This event occurs when the Interface agent reviews and validates a generated
 * API operation against business requirements, technical specifications, and
 * OpenAPI standards. The review phase ensures that the operation properly
 * implements the required functionality with correct request/response schemas,
 * authentication, error handling, and documentation.
 *
 * The review process involves systematic validation where the agent evaluates
 * operation completeness, parameter correctness, response accuracy, and API
 * design consistency. If the operation fails validation or violates
 * architectural principles, it may be corrected or removed (content set to
 * null).
 *
 * @author Kakasoo
 */
export interface AutoBeInterfaceOperationReviewEvent
  extends
    AutoBeEventBase<"interfaceOperationReview">,
    AutoBeProgressEventBase,
    AutoBeAggregateEventBase {
  /**
   * Original API operation submitted for review.
   *
   * The operation generated by the Interface Operations Agent that requires
   * validation for security compliance, schema alignment, logical consistency,
   * and adherence to AutoBE standards. This is the operation being evaluated
   * for potential issues and improvements.
   */
  operation: AutoBeOpenApi.IOperation;

  /**
   * Detailed review feedback from the Interface Operations Review Agent.
   *
   * Contains comprehensive assessment results including:
   *
   * - Security vulnerability analysis
   * - Schema compliance validation
   * - Logical consistency verification
   * - Standard adherence evaluation
   * - Identified critical issues and recommendations
   */
  review: string;

  /**
   * Amendment plan based on the review feedback.
   *
   * Structured action plan outlining specific corrections needed for:
   *
   * - Security issues (password exposure, authorization bypasses)
   * - Logic errors (mismatched return types, incorrect HTTP semantics)
   * - Schema violations (missing fields, type mismatches)
   *
   * If operations are perfect, explicitly states no changes are required.
   */
  plan: string;

  /**
   * Revised operation based on the amendment plan, or null if removed.
   *
   * The final corrected API operation after applying all fixes from the
   * improvement plan. If no issues were found during review, this contains the
   * original operation unchanged. If the operation violates fundamental
   * architectural principles or should be removed entirely, this is null. The
   * enhanced operation is ready for schema generation and subsequent
   * implementation phases.
   */
  content: AutoBeOpenApi.IOperation | null;

  /**
   * Current iteration number of the operation review process.
   *
   * Indicates which revision cycle of the API operation review is currently
   * being executed. This step number helps track the iterative validation
   * process and provides context for understanding how many review cycles have
   * been completed to achieve the desired operation quality.
   *
   * The step value increments with each major review iteration, allowing
   * stakeholders to monitor the progressive refinement of API operations and
   * understand the validation rigor applied to the interface design.
   */
  step: number;
}
