import { AutoBeTestScenario } from "../histories/contents/AutoBeTestScenario";
import { AutoBeOpenApi } from "../openapi/AutoBeOpenApi";
import { AutoBeAggregateEventBase } from "./base/AutoBeAggregateEventBase";
import { AutoBeEventBase } from "./base/AutoBeEventBase";
import { AutoBeProgressEventBase } from "./base/AutoBeProgressEventBase";

/**
 * Event emitted when a single test scenario's review is completed.
 *
 * This event is triggered when the Test Scenario Review Agent completes
 * analyzing one test scenario to validate authentication correctness,
 * dependency completeness, execution order, and business logic coverage.
 *
 * The review process examines the test scenario to identify issues such as:
 *
 * - Missing authentication operations
 * - Incomplete dependency chains
 * - Wrong execution order (auth should precede business operations)
 * - Validation-only tests (framework-level tests that should be removed)
 *
 * By extending multiple base interfaces, this event provides comprehensive
 * tracking capabilities including progress monitoring for one-by-one scenario
 * processing and token usage analytics for cost optimization.
 *
 * @author Michael
 */
export interface AutoBeTestScenarioReviewEvent
  extends
    AutoBeEventBase<"testScenarioReview">,
    AutoBeProgressEventBase,
    AutoBeAggregateEventBase {
  /**
   * The API endpoint being tested.
   *
   * Identifies the specific operation (method + path) that this test scenario
   * targets. Used to correlate the review result with the corresponding API
   * operation.
   */
  endpoint: AutoBeOpenApi.IEndpoint;

  /**
   * The original test scenario before review.
   *
   * Contains the initial scenario as generated by the Test Scenario Agent,
   * preserving the original for comparison and audit purposes.
   */
  original: AutoBeTestScenario;

  /**
   * The improved test scenario after review, or null if no improvements needed.
   *
   * - If `null`: The original scenario was already correct with no issues found
   * - If `AutoBeTestScenario`: Contains the improved version with fixes applied:
   *
   *   - Corrected authentication operations
   *   - Complete dependency chains
   *   - Proper execution order
   *   - Refined test descriptions
   *
   * The improved scenario maintains the same `endpoint` and `functionName` as
   * the original, ensuring consistency in test identification.
   */
  improved: AutoBeTestScenario | null;

  /**
   * Iteration number of the interface specification this review was performed
   * for.
   *
   * Indicates which version of the API specification this review reflects. This
   * step number ensures that the scenario review is aligned with the current
   * interface structure.
   *
   * The step value enables proper synchronization between scenario review and
   * the underlying interface definitions, ensuring that test scenarios remain
   * valid as the API evolves through iterations.
   */
  step: number;
}
