import { IAutoBeTokenUsageJson } from "../json/IAutoBeTokenUsageJson";
import { AutoBeOpenApi } from "../openapi";
import { AutoBeEventBase } from "./AutoBeEventBase";

/**
 * Event fired during the review and improvement phase of OpenAPI schema
 * generation process.
 *
 * This event represents the quality assurance activity of the Interface Schemas
 * Review Agent, which validates and enhances the OpenAPI schemas produced by
 * the Interface Schemas Agent. The reviewer ensures that all schemas meet
 * AutoBE's standards for type safety, completeness, and consistency before
 * being integrated into the final API specification.
 *
 * The Interface Schemas Review Agent performs comprehensive validation
 * including:
 *
 * - Schema completeness verification (all required properties defined)
 * - Type correctness and consistency across related schemas
 * - Proper use of OpenAPI schema features (allOf, oneOf, anyOf, etc.)
 * - Validation rules and constraints appropriateness
 * - Naming conventions and structural consistency
 * - Relationship integrity between interconnected schemas
 *
 * Review outcomes:
 *
 * - **Accept**: Schemas meet all criteria and can be used as-is
 * - **Improve**: Schemas are enhanced with better type definitions or constraints
 * - **Correct**: Critical issues are fixed to ensure proper API functionality
 *
 * Key characteristics of the review process:
 *
 * - Reviews all schemas holistically to ensure consistency
 * - Enhances schemas with additional validation rules when beneficial
 * - Ensures compatibility with Prisma models and business requirements
 * - Validates that schemas properly represent the API's data contracts
 *
 * The review ensures that the Interface Agent receives well-structured,
 * type-safe schemas that accurately represent the application's data models and
 * enable reliable API endpoint generation.
 *
 * @author Kakasoo
 */
export interface AutoBeInterfaceSchemasReviewEvent
  extends AutoBeEventBase<"interfaceSchemasReview"> {
  /**
   * Original schemas submitted for review.
   *
   * Contains the complete set of OpenAPI schemas generated by the Interface
   * Schemas Agent, including all data models, request/response types, and
   * shared definitions that need validation and potential enhancement.
   */
  schemas: Record<
    string,
    AutoBeOpenApi.IJsonSchemaDescriptive<AutoBeOpenApi.IJsonSchema>
  >;

  /**
   * Detailed review feedback from the Interface Schemas Review Agent.
   *
   * Contains specific validation results including:
   *
   * - Schema completeness assessment
   * - Type safety violations
   * - Naming convention issues
   * - Missing or incorrect relationships
   * - Validation rule recommendations
   * - Overall quality assessment and improvement suggestions
   */
  review: string;

  /**
   * Amendment plan based on the review feedback.
   *
   * Outlines specific changes to be made to improve the schemas. If the
   * original schemas are perfect and require no modifications, this field will
   * explicitly state that no changes are needed.
   *
   * The plan serves as a structured approach to enhance schemas, ensuring all
   * identified improvements are systematically applied.
   */
  plan: string;

  /**
   * Revised schemas based on the amendment plan.
   *
   * Contains the fully updated OpenAPI schemas incorporating all review
   * feedback and improvements. If the original schemas were perfect and
   * required no changes, this will be identical to the original schemas.
   *
   * These revised schemas must pass all validation criteria before being used
   * for API endpoint generation.
   */
  content: Record<
    string,
    AutoBeOpenApi.IJsonSchemaDescriptive<AutoBeOpenApi.IJsonSchema>
  >;

  /**
   * Current iteration number of the schema generation being reviewed.
   *
   * Indicates which version of the schemas is undergoing review and
   * improvement. This step number helps track the iterative refinement process
   * and provides context for understanding how many revision cycles have been
   * completed.
   */
  step: number;

  /**
   * Total number of schema sets to review in the current session.
   *
   * Represents the complete collection of schema groups that need validation.
   * Complex APIs may have multiple schema sets requiring individual review
   * cycles.
   */
  total: number;

  /**
   * Number of schema sets reviewed and finalized so far.
   *
   * Tracks progress through the review process when multiple schema collections
   * need validation. Each set must pass review before the count increments.
   */
  completed: number;

  /**
   * Token usage statistics for the schema review and enhancement process.
   *
   * Measures the computational resources consumed during the comprehensive
   * validation and improvement of OpenAPI schemas. This metric reflects the
   * complexity of analyzing schema completeness, type correctness, naming
   * conventions, validation rules, and relationship integrity across the
   * entire schema collection.
   *
   * The token usage increases with the depth of analysis required and the
   * number of improvements identified, as the review agent must evaluate
   * schemas holistically, formulate enhancement strategies, and generate
   * revised schemas that meet AutoBE's enterprise-level standards.
   */
  tokenUsage: IAutoBeTokenUsageJson.IComponent;
}
