/**
 * @packageDocumentation
 * @module api.functional.autobe.playground.vendors
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IAutoBePlaygroundVendor, IPage } from "@autobe/interface";
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { tags } from "typia";

export * as models from "./models/index";

/**
 * Register a new AI vendor configuration.
 *
 * Stores the vendor's endpoint and concurrency settings. The API key is
 * encrypted before persistence and never returned in any response.
 *
 * @param body Vendor creation properties
 * @author Samchon
 * @returns Newly created vendor record
 * @tag Vendor
 *
 * @controller AutoBePlaygroundVendorController.create
 * @path POST /autobe/playground/vendors
 * @accessor api.functional.autobe.playground.vendors.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    body,
  );
}
export namespace create {
  export type Body = IAutoBePlaygroundVendor.ICreate;
  export type Output = IAutoBePlaygroundVendor;

  export const METADATA = {
    method: "POST",
    path: "/autobe/playground/vendors",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/autobe/playground/vendors";
}

/**
 * List vendor configurations with pagination.
 *
 * Returns a paginated list of all registered vendor configurations, sorted by
 * creation date in descending order. Soft-deleted vendors are excluded.
 *
 * @param body Pagination request parameters
 * @author Samchon
 * @returns Paginated vendor list
 * @tag Vendor
 *
 * @controller AutoBePlaygroundVendorController.index
 * @path PATCH /autobe/playground/vendors
 * @accessor api.functional.autobe.playground.vendors.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(),
    },
    body,
  );
}
export namespace index {
  export type Body = IPage.IRequest;
  export type Output = IPage<IAutoBePlaygroundVendor>;

  export const METADATA = {
    method: "PATCH",
    path: "/autobe/playground/vendors",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/autobe/playground/vendors";
}

/**
 * Get a vendor configuration by ID.
 *
 * @param id Target vendor's {@link IAutoBePlaygroundVendor.id }
 * @author Samchon
 * @returns Vendor record
 * @tag Vendor
 *
 * @controller AutoBePlaygroundVendorController.at
 * @path GET /autobe/playground/vendors/:id
 * @accessor api.functional.autobe.playground.vendors.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  id: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(id),
  });
}
export namespace at {
  export type Output = IAutoBePlaygroundVendor;

  export const METADATA = {
    method: "GET",
    path: "/autobe/playground/vendors/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & tags.Format<"uuid">) =>
    `/autobe/playground/vendors/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * Update a vendor configuration.
 *
 * Only the provided fields are updated. If a new API key is supplied, it is
 * re-encrypted before storage.
 *
 * @param id Target vendor's {@link IAutoBePlaygroundVendor.id }
 * @param body Fields to update
 * @author Samchon
 * @tag Vendor
 *
 * @controller AutoBePlaygroundVendorController.update
 * @path PUT /autobe/playground/vendors/:id
 * @accessor api.functional.autobe.playground.vendors.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(id),
    },
    body,
  );
}
export namespace update {
  export type Body = IAutoBePlaygroundVendor.IUpdate;

  export const METADATA = {
    method: "PUT",
    path: "/autobe/playground/vendors/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & tags.Format<"uuid">) =>
    `/autobe/playground/vendors/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * Soft-delete a vendor configuration.
 *
 * Marks the vendor as deleted without physically removing the record.
 * Sessions that previously used this vendor remain intact.
 *
 * @param id Target vendor's {@link IAutoBePlaygroundVendor.id }
 * @author Samchon
 * @tag Vendor
 *
 * @controller AutoBePlaygroundVendorController.erase
 * @path DELETE /autobe/playground/vendors/:id
 * @accessor api.functional.autobe.playground.vendors.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  id: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(id),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/autobe/playground/vendors/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & tags.Format<"uuid">) =>
    `/autobe/playground/vendors/${encodeURIComponent(id?.toString() ?? "null")}`;
}
