/**
 * @packageDocumentation
 * @module api.functional.autobe.playground.vendors
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IPage } from "@autobe/interface";
import type { IAutoBePlaygroundVendor } from "@autobe/playground-api";
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

/**
 * @controller AutoBePlaygroundVendorController.create
 * @path POST /autobe/playground/vendors
 * @accessor api.functional.autobe.playground.vendors.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IAutoBePlaygroundVendor.ICreate>;
  export type Output = Primitive<IAutoBePlaygroundVendor>;

  export const METADATA = {
    method: "POST",
    path: "/autobe/playground/vendors",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/autobe/playground/vendors";
}

/**
 * @controller AutoBePlaygroundVendorController.index
 * @path PATCH /autobe/playground/vendors
 * @accessor api.functional.autobe.playground.vendors.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IPage.IRequest>;
  export type Output = Primitive<IPage<IAutoBePlaygroundVendor>>;

  export const METADATA = {
    method: "PATCH",
    path: "/autobe/playground/vendors",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/autobe/playground/vendors";
}

/**
 * @controller AutoBePlaygroundVendorController.at
 * @path GET /autobe/playground/vendors/:id
 * @accessor api.functional.autobe.playground.vendors.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  id: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(id),
  });
}
export namespace at {
  export type Output = Primitive<IAutoBePlaygroundVendor>;

  export const METADATA = {
    method: "GET",
    path: "/autobe/playground/vendors/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & tags.Format<"uuid">) =>
    `/autobe/playground/vendors/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller AutoBePlaygroundVendorController.update
 * @path PUT /autobe/playground/vendors/:id
 * @accessor api.functional.autobe.playground.vendors.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(id),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IAutoBePlaygroundVendor.IUpdate>;

  export const METADATA = {
    method: "PUT",
    path: "/autobe/playground/vendors/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & tags.Format<"uuid">) =>
    `/autobe/playground/vendors/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller AutoBePlaygroundVendorController.erase
 * @path DELETE /autobe/playground/vendors/:id
 * @accessor api.functional.autobe.playground.vendors.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  id: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(id),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/autobe/playground/vendors/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & tags.Format<"uuid">) =>
    `/autobe/playground/vendors/${encodeURIComponent(id?.toString() ?? "null")}`;
}
