import { IConnection, HttpError } from "@nestia/fetcher";
import typia, { tags } from "typia";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

;
import { IShoppingCart } from "../../../structures/IShoppingCart";
export * as commodities from "./commodities";
/**
 * Retrieves the given customer's entire shopping cart, including all currently active (not deleted/published) commodities and their chosen options.
 *
 * @param customerId Unique customer ID (owner of the cart).
 * @path /shopping/carts/:customerId
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
*/
export async function getByCustomerid(connection: IConnection, customerId: string & tags.Format<"uuid">): Promise<getByCustomerid.Output> {
    return !!connection.simulate ? getByCustomerid.simulate(connection, customerId) : PlainFetcher.fetch({
        ...connection,
        headers: {
            ...connection.headers,
            "Content-Type": "application/json"
        }
    }, {
        ...getByCustomerid.METADATA,
        path: getByCustomerid.path(customerId),
        status: null
    });
}
export namespace getByCustomerid {
    export type Output = IShoppingCart;
    
    ;
    export const METADATA = {
        method: "GET",
        path: "/shopping/carts/:customerId",
        request: null,
        response: {
            type: "application/json",
            encrypted: false
        }
    } as const;
    
    ;
    export const path = (customerId: string & tags.Format<"uuid">) => `/shopping/carts/${encodeURIComponent(customerId ?? "null")}`;
    export const random = (g?: Partial<typia.IRandomGenerator>): IShoppingCart => typia.random<IShoppingCart>(g);
    export const simulate = (connection: IConnection, customerId: string & tags.Format<"uuid">): Output => {
        const assert = NestiaSimulator.assert({
            method: METADATA.method,
            host: connection.host,
            path: getByCustomerid.path(customerId),
            contentType: "application/json"
        });
        try {
            assert.param("customerId")(() => typia.assert(customerId));
        }
        catch (exp) {
            if (!typia.is<HttpError>(exp))
                throw exp;
            return {
                success: false,
                status: exp.status,
                headers: exp.headers,
                data: exp.toJSON().message
            } as any;
        }
        return random("object" === typeof connection.simulate && null !== connection.simulate ? connection.simulate : undefined);
    };
}
