import { AutoBeDatabaseGroup } from "@autobe/interface";
import { StringUtil } from "@autobe/utils";
import { v7 } from "uuid";

import { AutoBeSystemPromptConstant } from "../../../constants/AutoBeSystemPromptConstant";
import { IAutoBeOrchestrateHistory } from "../../../structures/IAutoBeOrchestrateHistory";
import { AutoBePreliminaryController } from "../../common/AutoBePreliminaryController";

export const transformPrismaGroupReviewHistory = (props: {
  preliminary: AutoBePreliminaryController<
    "analysisSections" | "previousAnalysisSections" | "previousDatabaseSchemas"
  >;
  groups: AutoBeDatabaseGroup[];
  instruction: string;
}): IAutoBeOrchestrateHistory => ({
  histories: [
    {
      id: v7(),
      created_at: new Date().toISOString(),
      type: "systemMessage",
      text: AutoBeSystemPromptConstant.DATABASE_GROUP,
    },
    {
      id: v7(),
      created_at: new Date().toISOString(),
      type: "systemMessage",
      text: AutoBeSystemPromptConstant.DATABASE_GROUP_REVIEW,
    },
    ...props.preliminary.getHistories(),
    {
      id: v7(),
      created_at: new Date().toISOString(),
      type: "assistantMessage",
      text: StringUtil.trim`
        ## Component Groups to Review

        The following component group skeletons were generated by the Database Group Agent.
        Review them against the business requirements and apply necessary revisions.

        ### Current Groups

        \`\`\`json
        ${JSON.stringify(props.groups)}
        \`\`\`

        ### User Instructions

        ${props.instruction}
      `,
    },
  ],
  userMessage: StringUtil.trim`
    Review the component group structure and apply necessary revisions.

    **🚨 CRITICAL: Authorization Group is PROTECTED**
    - The authorization group (\`kind: "authorization"\`) is **IMMUTABLE**
    - You can ONLY review and revise **domain groups** (\`kind: "domain"\`)
    - ❌ Cannot create/update/erase authorization groups

    **Group Structure Rules:**
    - Exactly 1 group with \`kind: "authorization"\` - DO NOT MODIFY
    - At least 1 group with \`kind: "domain"\` (for business domain tables)
    - Each domain group should cover a focused business domain (3-15 estimated tables)
    - Namespace must be PascalCase, filename must follow \`schema-{number}-{domain}.prisma\` format

    **Steps:**
    1. Fetch analysis files using \`getAnalysisSections\` to understand business requirements
    2. Verify every business domain has a corresponding domain group
    3. Check domain group boundaries and naming conventions (skip authorization group)
    4. Call \`process({ request: { type: "complete", review: "...", revises: [...] } })\`

    **Revisions (domain groups only):**
    - **Create**: Add domain groups for missing business domains (\`kind: "domain"\` only)
    - **Update**: Fix domain groups with naming or scope issues
    - **Erase**: Remove redundant domain groups

    If no changes are needed, return an empty revises array.
  `,
});
