import { AutoBeDatabaseGroup } from "@autobe/interface";
import { StringUtil } from "@autobe/utils";
import { v7 } from "uuid";

import { AutoBeSystemPromptConstant } from "../../../constants/AutoBeSystemPromptConstant";
import { IAutoBeOrchestrateHistory } from "../../../structures/IAutoBeOrchestrateHistory";
import { AutoBePreliminaryController } from "../../common/AutoBePreliminaryController";

export const transformPrismaGroupReviewHistory = (props: {
  preliminary: AutoBePreliminaryController<
    "analysisFiles" | "previousAnalysisFiles" | "previousDatabaseSchemas"
  >;
  groups: AutoBeDatabaseGroup[];
  instruction: string;
}): IAutoBeOrchestrateHistory => ({
  histories: [
    {
      id: v7(),
      created_at: new Date().toISOString(),
      type: "systemMessage",
      text: AutoBeSystemPromptConstant.DATABASE_GROUP,
    },
    {
      id: v7(),
      created_at: new Date().toISOString(),
      type: "systemMessage",
      text: AutoBeSystemPromptConstant.DATABASE_GROUP_REVIEW,
    },
    ...props.preliminary.getHistories(),
    {
      id: v7(),
      created_at: new Date().toISOString(),
      type: "assistantMessage",
      text: StringUtil.trim`
        ## Component Groups to Review

        The following component group skeletons were generated by the Database Group Agent.
        Review them against the business requirements and apply necessary revisions.

        ### Current Groups

        ${JSON.stringify(props.groups, null, 2)}

        ### User Instructions

        ${props.instruction}
      `,
    },
  ],
  userMessage: StringUtil.trim`
    Review the component group structure and apply necessary revisions.

    **Group Structure Rules:**
    - Exactly 1 group with \`kind: "authorization"\` (for actor/authentication tables)
    - At least 1 group with \`kind: "domain"\` (for business domain tables)
    - Each group should cover a focused business domain (3-15 estimated tables)
    - Namespace must be PascalCase, filename must follow \`schema-{number}-{domain}.prisma\` format

    1. First, fetch analysis files using \`getAnalysisFiles\` to understand business requirements
    2. Verify every business domain has a corresponding group
    3. Check group boundaries, kind assignments, and naming conventions
    4. Call \`process({ request: { type: "complete", revises: [...] } })\` with your revisions

    Use revises to:
    - **Create**: Add groups for missing business domains
    - **Update**: Fix groups with naming, kind, or scope issues
    - **Erase**: Remove redundant or unnecessary groups

    If no changes are needed, return an empty revises array.
  `,
});
