import { AutoBeAnalyzeWriteDocumentEvent } from "@autobe/interface/src/events/AutoBeAnalyzeWriteDocumentEvent";
import Button from "@mui/material/Button";
import StackBlitzSDK from "@stackblitz/sdk";
import { useCallback } from "react";

export function AutoBePlaygroundAnalyzeWriteDocumentMovie(props: {
  event: AutoBeAnalyzeWriteDocumentEvent;
}) {
  return (
    <ul>
      <li>
        <Files files={props.event.files} />
      </li>
    </ul>
  );
}

function Files(props: { files: Record<string, string> }) {
  const openStackBlitz = useCallback(() => {
    const files = {
      ...props.files,
      "index.html": `<h1>Generated by AutoBE</h1><p>these markdown files are generated by AutoBE.</p><script src="index.ts"></script>`,
      "index.ts": `document.body.style.background = "lightblue";`,
    };

    StackBlitzSDK.openProject(
      {
        files,
        title: "AutoBe Analyze Write Document",
        description:
          "This is a project generated by AutoBe Analyze Write Document.",
        template: "typescript",
      },
      {
        newWindow: true,
      },
    );
  }, [props.files]);

  return (
    <details>
      <summary>current generated files</summary>
      <p>Click this button to open and read the file in StackBlitz</p>
      <Button onClick={openStackBlitz}>Open</Button>
    </details>
  );
}
