import { AutoBeOpenApi, IAutoBeInterfaceCompiler } from "@autobe/interface";
import { NestiaMigrateApplication } from "@nestia/migrate";
import { OpenApi, OpenApiV3_1 } from "@samchon/openapi";
import sortImport from "@trivago/prettier-plugin-sort-imports";
import import2 from "import2";
import { format } from "prettier";

import { AutoBeCompilerConstants } from "./raw/AutoBeCompilerConstants";
import { ArrayUtil } from "./utils/ArrayUtil";

export class AutoBeInterfaceCompiler implements IAutoBeInterfaceCompiler {
  public async compile(
    document: AutoBeOpenApi.IDocument,
  ): Promise<Record<string, string>> {
    const swagger: OpenApi.IDocument = createOpenApiDocument(document);
    const migrate: NestiaMigrateApplication = new NestiaMigrateApplication(
      swagger,
    );
    const files: Record<string, string> = migrate.nest({
      keyword: true,
      simulate: true,
      e2e: true,
      author: {
        tag: "autobe",
        value: "Generated by AutoBE - https://github.com/wrtnlabs/autobe",
      },
    });
    return {
      ...Object.fromEntries(
        await ArrayUtil.asyncMap(
          Object.entries(files),
          async ([key, value]) => [
            key,
            key.endsWith(".ts") && key.endsWith(".d.ts") === false
              ? await beautify(value)
              : value,
          ],
        ),
      ),
      "packages/api/swagger.json": JSON.stringify(swagger, null, 2),
      "README.md": AutoBeCompilerConstants.README,
    };
  }
}

async function beautify(script: string) {
  try {
    return await format(script, {
      parser: "typescript",
      plugins: [sortImport, await import2("prettier-plugin-jsdoc")],
      importOrder: ["<THIRD_PARTY_MODULES>", "^[./]"],
      importOrderSeparation: true,
      importOrderSortSpecifiers: true,
      importOrderParserPlugins: ["decorators-legacy", "typescript", "jsx"],
    });
  } catch {
    return script;
  }
}

function createOpenApiDocument(
  route: AutoBeOpenApi.IDocument,
): OpenApi.IDocument {
  const paths: Record<string, OpenApi.IPath> = {};
  for (const op of route.operations) {
    paths[op.path] ??= {};
    paths[op.path][op.method] = {
      summary: op.summary,
      description: op.description,
      parameters: op.parameters.map((p) => ({
        name: p.name,
        in: "path",
        schema: p.schema,
        description: p.description,
        required: true,
      })),
      requestBody: op.requestBody
        ? {
            content: {
              "application/json": {
                schema: {
                  $ref: `#.components/schemas/${op.requestBody.typeName}`,
                },
              },
            },
            description: op.requestBody.description,
            required: true,
          }
        : undefined,
      responses: op.responseBody
        ? {
            [op.method === "post" ? 201 : 200]: {
              content: {
                "application/json": {
                  schema: {
                    $ref: `#/components/schemas/${op.responseBody.typeName}`,
                  },
                },
              },
              description: op.responseBody.description,
            },
          }
        : undefined,
    };
  }
  return OpenApi.convert({
    openapi: "3.1.0",
    paths,
    components: route.components,
  } as OpenApiV3_1.IDocument);
}
