/**
 * @packageDocumentation
 * @module api.functional.autobe.playground
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type {
  IAutoBePlaygroundHeader,
  IAutoBeRpcListener,
  IAutoBeRpcService,
} from "@autobe/interface";
import type { IConnection } from "@nestia/fetcher";
import { WebSocketConnector } from "tgrid";
import type { Driver } from "tgrid";

export * as replay from "./replay/index";

/**
 * @controller AutoBePlaygroundController.start
 * @path /autobe/playground/start
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function start(
  connection: IConnection<start.Header>,
  provider: start.Provider,
): Promise<start.Output> {
  const url: string = `${connection.host.endsWith("/") ? connection.host.substring(0, connection.host.length - 1) : connection.host}${start.path()}`;
  const connector: WebSocketConnector<
    start.Header,
    start.Provider,
    start.Listener
  > = new WebSocketConnector(connection.headers ?? ({} as any), provider);
  await connector.connect(url);
  const driver: Driver<start.Listener> = connector.getDriver();
  return {
    connector,
    driver,
    reconnect: async () => await connector.connect(url),
  };
}
export namespace start {
  export type Output = {
    connector: WebSocketConnector<Header, Provider, Listener>;
    driver: Driver<Listener>;
    reconnect: () => Promise<void>;
  };
  export type Header = IAutoBePlaygroundHeader;
  export type Provider = IAutoBeRpcListener;
  export type Listener = IAutoBeRpcService;

  export const path = () => "/autobe/playground/start";
}
