/**
 * @packageDocumentation
 * @module api.functional.autobe.playground.sessions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type {
  IAutoBeRpcListener,
  IAutoBeRpcService,
  IPage,
} from "@autobe/interface";
import type { IAutoBePlaygroundSession } from "@autobe/playground-api";
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import { WebSocketConnector } from "tgrid";
import type { Driver } from "tgrid";
import type { Primitive, tags } from "typia";

/**
 * @controller AutoBePlaygroundSessionController.create
 * @path POST /autobe/playground/sessions
 * @accessor api.functional.autobe.playground.sessions.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IAutoBePlaygroundSession.ICreate>;
  export type Output = Primitive<IAutoBePlaygroundSession>;

  export const METADATA = {
    method: "POST",
    path: "/autobe/playground/sessions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/autobe/playground/sessions";
}

/**
 * @controller AutoBePlaygroundSessionController.index
 * @path PATCH /autobe/playground/sessions
 * @accessor api.functional.autobe.playground.sessions.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IPage.IRequest>;
  export type Output = Primitive<IPage<IAutoBePlaygroundSession.ISummary>>;

  export const METADATA = {
    method: "PATCH",
    path: "/autobe/playground/sessions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/autobe/playground/sessions";
}

/**
 * @controller AutoBePlaygroundSessionController.at
 * @path GET /autobe/playground/sessions/:id
 * @accessor api.functional.autobe.playground.sessions.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  id: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(id),
  });
}
export namespace at {
  export type Output = Primitive<IAutoBePlaygroundSession>;

  export const METADATA = {
    method: "GET",
    path: "/autobe/playground/sessions/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & tags.Format<"uuid">) =>
    `/autobe/playground/sessions/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller AutoBePlaygroundSessionController.update
 * @path PUT /autobe/playground/sessions/:id
 * @accessor api.functional.autobe.playground.sessions.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(id),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IAutoBePlaygroundSession.IUpdate>;

  export const METADATA = {
    method: "PUT",
    path: "/autobe/playground/sessions/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & tags.Format<"uuid">) =>
    `/autobe/playground/sessions/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller AutoBePlaygroundSessionController.erase
 * @path DELETE /autobe/playground/sessions/:id
 * @accessor api.functional.autobe.playground.sessions.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  id: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(id),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/autobe/playground/sessions/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & tags.Format<"uuid">) =>
    `/autobe/playground/sessions/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller AutoBePlaygroundSessionSocketController.connect
 * @path /autobe/playground/sessions/:id/connect
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function connect(
  connection: IConnection<connect.Header>,
  id: string & tags.Format<"uuid">,
  provider: connect.Provider,
): Promise<connect.Output> {
  const url: string = `${connection.host.endsWith("/") ? connection.host.substring(0, connection.host.length - 1) : connection.host}${connect.path(id)}`;
  const connector: WebSocketConnector<
    connect.Header,
    connect.Provider,
    connect.Listener
  > = new WebSocketConnector(connection.headers ?? ({} as any), provider);
  await connector.connect(url);
  const driver: Driver<connect.Listener> = connector.getDriver();
  return {
    connector,
    driver,
    reconnect: async () => await connector.connect(url),
  };
}
export namespace connect {
  export type Output = {
    connector: WebSocketConnector<Header, Provider, Listener>;
    driver: Driver<Listener>;
    reconnect: () => Promise<void>;
  };
  export type Header = void;
  export type Provider = IAutoBeRpcListener;
  export type Listener = IAutoBeRpcService;

  export const path = (id: string & tags.Format<"uuid">) =>
    `/autobe/playground/sessions/${encodeURIComponent(id?.toString() ?? "null")}/connect`;
}

/**
 * @controller AutoBePlaygroundSessionSocketController.replay
 * @path /autobe/playground/sessions/:id/replay
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function replay(
  connection: IConnection<replay.Header>,
  id: string & tags.Format<"uuid">,
  provider: replay.Provider,
): Promise<replay.Output> {
  const url: string = `${connection.host.endsWith("/") ? connection.host.substring(0, connection.host.length - 1) : connection.host}${replay.path(id)}`;
  const connector: WebSocketConnector<
    replay.Header,
    replay.Provider,
    replay.Listener
  > = new WebSocketConnector(connection.headers ?? ({} as any), provider);
  await connector.connect(url);
  const driver: Driver<replay.Listener> = connector.getDriver();
  return {
    connector,
    driver,
    reconnect: async () => await connector.connect(url),
  };
}
export namespace replay {
  export type Output = {
    connector: WebSocketConnector<Header, Provider, Listener>;
    driver: Driver<Listener>;
    reconnect: () => Promise<void>;
  };
  export type Header = void;
  export type Provider = IAutoBeRpcListener;
  export type Listener = IAutoBeRpcService;

  export const path = (id: string & tags.Format<"uuid">) =>
    `/autobe/playground/sessions/${encodeURIComponent(id?.toString() ?? "null")}/replay`;
}
