/**
 * @packageDocumentation
 * @module api.functional.autobe.playground.sessions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type {
  IAutoBePlaygroundSession,
  IAutoBeRpcListener,
  IAutoBeRpcService,
  IPage,
} from "@autobe/interface";
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import { WebSocketConnector } from "tgrid";
import type { Driver } from "tgrid";
import type { tags } from "typia";

/**
 * List sessions with pagination.
 *
 * Returns a paginated list of session summaries sorted by creation date in
 * descending order. Soft-deleted sessions are excluded.
 *
 * @param body Search and pagination request parameters
 * @author Samchon
 * @returns Paginated session summary list
 * @tag Session
 *
 * @controller AutoBePlaygroundSessionController.index
 * @path PATCH /autobe/playground/sessions
 * @accessor api.functional.autobe.playground.sessions.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(),
    },
    body,
  );
}
export namespace index {
  export type Body = IAutoBePlaygroundSession.IRequest;
  export type Output = IPage<IAutoBePlaygroundSession.ISummary>;

  export const METADATA = {
    method: "PATCH",
    path: "/autobe/playground/sessions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/autobe/playground/sessions";
}

/**
 * Get a session by ID with full detail.
 *
 * Returns the complete session record including all conversation histories
 * and event snapshots.
 *
 * @param id Target session's {@link IAutoBePlaygroundSession.id }
 * @author Samchon
 * @returns Session with histories and snapshots
 * @tag Session
 *
 * @controller AutoBePlaygroundSessionController.at
 * @path GET /autobe/playground/sessions/:id
 * @accessor api.functional.autobe.playground.sessions.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  id: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(id),
  });
}
export namespace at {
  export type Output = IAutoBePlaygroundSession;

  export const METADATA = {
    method: "GET",
    path: "/autobe/playground/sessions/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & tags.Format<"uuid">) =>
    `/autobe/playground/sessions/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * Create a new vibe coding session.
 *
 * Creates a session bound to a stored vendor configuration. The vendor's
 * decrypted API key will be used when establishing the AI agent connection.
 *
 * @param body Session creation properties
 * @author Samchon
 * @returns Newly created session with full detail
 * @tag Session
 *
 * @controller AutoBePlaygroundSessionController.create
 * @path POST /autobe/playground/sessions
 * @accessor api.functional.autobe.playground.sessions.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    body,
  );
}
export namespace create {
  export type Body = IAutoBePlaygroundSession.ICreate;
  export type Output = IAutoBePlaygroundSession;

  export const METADATA = {
    method: "POST",
    path: "/autobe/playground/sessions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/autobe/playground/sessions";
}

/**
 * Update a session's metadata.
 *
 * Currently supports updating the session title only.
 *
 * @param id Target session's {@link IAutoBePlaygroundSession.id }
 * @param body Fields to update
 * @author Samchon
 * @tag Session
 *
 * @controller AutoBePlaygroundSessionController.update
 * @path PUT /autobe/playground/sessions/:id
 * @accessor api.functional.autobe.playground.sessions.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(id),
    },
    body,
  );
}
export namespace update {
  export type Body = IAutoBePlaygroundSession.IUpdate;

  export const METADATA = {
    method: "PUT",
    path: "/autobe/playground/sessions/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & tags.Format<"uuid">) =>
    `/autobe/playground/sessions/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * Soft-delete a session.
 *
 * Marks the session as deleted without physically removing the record or its
 * associated histories, events, and connections.
 *
 * @param id Target session's {@link IAutoBePlaygroundSession.id }
 * @author Samchon
 * @tag Session
 *
 * @controller AutoBePlaygroundSessionController.erase
 * @path DELETE /autobe/playground/sessions/:id
 * @accessor api.functional.autobe.playground.sessions.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  id: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(id),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/autobe/playground/sessions/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & tags.Format<"uuid">) =>
    `/autobe/playground/sessions/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * Connect to a session via WebSocket for real-time vibe coding.
 *
 * Establishes a bidirectional RPC connection to the AI agent. A new
 * connection record is created and the agent begins processing user
 * instructions. Events and histories are persisted to the database in real
 * time.
 *
 * @author Samchon
 * @param id Target session's {@link IAutoBePlaygroundSession.id }
 * @tag Session
 *
 * @controller AutoBePlaygroundSessionSocketController.connect
 * @path /autobe/playground/sessions/:id/connect
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function connect(
  connection: IConnection<connect.Header>,
  id: string & tags.Format<"uuid">,
  provider: connect.Provider,
): Promise<connect.Output> {
  const url: string = `${connection.host.endsWith("/") ? connection.host.substring(0, connection.host.length - 1) : connection.host}${connect.path(id)}`;
  const connector: WebSocketConnector<
    connect.Header,
    connect.Provider,
    connect.Listener
  > = new WebSocketConnector(connection.headers ?? ({} as any), provider);
  await connector.connect(url);
  const driver: Driver<connect.Listener> = connector.getDriver();
  return {
    connector,
    driver,
    reconnect: async () => await connector.connect(url),
  };
}
export namespace connect {
  export type Output = {
    connector: WebSocketConnector<Header, Provider, Listener>;
    driver: Driver<Listener>;
    reconnect: () => Promise<void>;
  };
  export type Header = any;
  export type Provider = IAutoBeRpcListener;
  export type Listener = IAutoBeRpcService;

  export const path = (id: string & tags.Format<"uuid">) =>
    `/autobe/playground/sessions/${encodeURIComponent(id?.toString() ?? "null")}/connect`;
}

/**
 * Replay a completed session via WebSocket.
 *
 * Re-streams all previously recorded events from the session, allowing the
 * client to reconstruct the full session state. The replayed connection is
 * read-only; user input is disabled.
 *
 * @author Samchon
 * @param id Target session's {@link IAutoBePlaygroundSession.id }
 * @tag Session
 *
 * @controller AutoBePlaygroundSessionSocketController.replay
 * @path /autobe/playground/sessions/:id/replay
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function replay(
  connection: IConnection<replay.Header>,
  id: string & tags.Format<"uuid">,
  provider: replay.Provider,
): Promise<replay.Output> {
  const url: string = `${connection.host.endsWith("/") ? connection.host.substring(0, connection.host.length - 1) : connection.host}${replay.path(id)}`;
  const connector: WebSocketConnector<
    replay.Header,
    replay.Provider,
    replay.Listener
  > = new WebSocketConnector(connection.headers ?? ({} as any), provider);
  await connector.connect(url);
  const driver: Driver<replay.Listener> = connector.getDriver();
  return {
    connector,
    driver,
    reconnect: async () => await connector.connect(url),
  };
}
export namespace replay {
  export type Output = {
    connector: WebSocketConnector<Header, Provider, Listener>;
    driver: Driver<Listener>;
    reconnect: () => Promise<void>;
  };
  export type Header = any;
  export type Provider = IAutoBeRpcListener;
  export type Listener = IAutoBeRpcService;

  export const path = (id: string & tags.Format<"uuid">) =>
    `/autobe/playground/sessions/${encodeURIComponent(id?.toString() ?? "null")}/replay`;
}
