"use client";

import AutoBeDemoMovie from "../demo/AutoBeDemoMovie";
import FadeIn from "./FadeIn";

export default function AutoBeLandingDemoMovie(
  props: AutoBeLandingDemoMovie.IProps,
) {
  return (
    <section className="py-40 px-6 bg-neutral-950">
      <div className="max-w-5xl mx-auto">
        {/* LEFT-aligned header */}
        <FadeIn className="max-w-xl mb-20">
          <p className="text-xs font-medium tracking-[0.3em] uppercase text-neutral-600 mb-6">
            Real Examples
          </p>
          <h2 className="text-4xl md:text-6xl font-bold text-white tracking-tight leading-[1.1] mb-5">
            Proven across
            <br />
            <span className="text-neutral-500">multiple models</span>
          </h2>
          <p className="text-base text-neutral-500 leading-relaxed">
            See real outputs generated by different AI models — complete with
            benchmarks, token usage, and pipeline details.
          </p>
        </FadeIn>
        <FadeIn delay={150}>
          <AutoBeDemoMovie model={props.model} />
        </FadeIn>
      </div>
    </section>
  );
}
export namespace AutoBeLandingDemoMovie {
  export interface IProps {
    model?: string;
  }
}
