import { AutoBeTest } from "../../test/AutoBeTest";
import { AutoBeTestScenario } from "./AutoBeTestScenario";

/**
 * Represents a single test file generated by the Test agent with comprehensive
 * scenario metadata and structured AST representation.
 *
 * Each test file encapsulates a specific testing scenario with its file system
 * location, structured AST function definition, generated TypeScript source
 * code, and detailed scenario information. This structure provides rich context
 * about the test's purpose, target API endpoints, and expected behavior
 * patterns, enabling better test organization, maintenance, and programmatic
 * manipulation.
 *
 * The workflow follows a clear progression: AST definition → TypeScript code
 * generation → executable test file, allowing for sophisticated analysis,
 * transformation, and code generation workflows.
 *
 * @author Kakasoo
 */
export interface AutoBeTestFile {
  /**
   * File system path where the test file should be located.
   *
   * Specifies the relative or absolute path for the test file within the
   * project structure. This location typically follows testing conventions and
   * may be organized by API endpoints, feature modules, or business domains to
   * ensure logical test suite organization and easy navigation.
   *
   * Example: "test/features/api/order/test_api_shopping_order_publish.ts"
   */
  location: string;

  /**
   * Structured AST representation of the test function.
   *
   * Contains the complete Abstract Syntax Tree definition of the test function,
   * including the strategic plan, draft implementation, and structured
   * statements array. This serves as the authoritative source representation of
   * the test logic before code generation.
   *
   * The AST representation includes:
   *
   * - Strategic planning documentation for implementation approach
   * - Draft TypeScript code showing the intended implementation
   * - Structured statements array representing the complete test flow
   *
   * This structured format allows tools to understand and manipulate test logic
   * at a semantic level, enabling sophisticated testing frameworks, analysis
   * tools, and programmatic modifications before final code generation.
   */
  function: AutoBeTest.IFunction;

  /**
   * Generated TypeScript source code compiled from the AST function.
   *
   * This is the executable TypeScript code automatically generated by
   * transforming the structured `function` AST representation into
   * syntactically correct TypeScript source code. The content represents the
   * final, runnable test implementation that can be executed by testing
   * frameworks.
   *
   * The code generation process converts:
   *
   * - AST statements into TypeScript function bodies
   * - API operation statements into SDK function calls
   * - Predicate expressions into TestValidator assertions
   * - Random generators into appropriate test data creation calls
   * - All other AST constructs into their corresponding TypeScript syntax
   *
   * This generated content includes all necessary imports, function
   * declarations, variable assignments, API calls, validations, and error
   * handling that comprise a complete end-to-end test scenario. The code is
   * ready for immediate execution without manual modifications.
   */
  content: string;

  /**
   * Detailed metadata describing the test scenario and its characteristics.
   *
   * Provides comprehensive information about what this test file covers,
   * including the specific API endpoints being tested, the business scenarios
   * being validated, expected outcomes, and any special conditions or
   * prerequisites. This metadata helps developers understand the test's purpose
   * and scope without having to analyze the AST structure or generated code.
   *
   * The scenario information is crucial for test maintenance, coverage
   * analysis, and ensuring that all business requirements are adequately tested
   * across the test suite. It serves as high-level documentation that
   * complements both the structured AST representation and the generated
   * executable TypeScript code.
   */
  scenario: AutoBeTestScenario;
}
