import { AutoBeTestScenario } from "./AutoBeTestScenario";
import { AutoBeTestWriteFunctionBase } from "./AutoBeTestWriteFunctionBase";

/**
 * Test writing function content structure for individual test scenario files.
 *
 * This interface represents the structured content generated by the test write
 * agent when creating comprehensive E2E test files. Each instance encapsulates
 * the complete lifecycle of a test file creation, from initial scenario
 * planning through code drafting, review, and final polished implementation.
 *
 * The test write function content enables systematic development of validation
 * suites that ensure generated applications function correctly under realistic
 * operational conditions. By capturing scenario descriptions, implementation
 * code, and iterative refinements, this structure supports both immediate test
 * file generation and long-term quality assurance practices.
 *
 * @author Michael
 */
export interface AutoBeTestWriteFunction
  extends AutoBeTestWriteFunctionBase<"write"> {
  /**
   * Detailed metadata describing the test scenario and its characteristics.
   *
   * Provides comprehensive information about what this test file covers,
   * including the specific API endpoints being tested, the business scenarios
   * being validated, expected outcomes, and any special conditions or
   * prerequisites. This metadata helps developers understand the test's purpose
   * and scope without having to analyze the AST structure or generated code.
   *
   * The scenario information is crucial for test maintenance, coverage
   * analysis, and ensuring that all business requirements are adequately tested
   * across the test suite. It serves as high-level documentation that
   * complements both the structured AST representation and the generated
   * executable TypeScript code.
   */
  scenario: Omit<AutoBeTestScenario, "functionName">;

  /**
   * Functional domain category for test classification and organization.
   *
   * Primary business or API resource domain that this test validates, used for
   * logical grouping and file structure organization. Common domains include
   * core business entities like "user", "order", "payment", "inventory", or
   * "notification" that represent major functional areas of the application.
   *
   * The domain classification helps developers quickly locate relevant tests
   * and understand the scope of validation coverage across different business
   * areas.
   */
  domain: string;

  /**
   * Initial test code implementation draft.
   *
   * First working version of the TypeScript E2E test function that implements
   * the complete business scenario. This draft includes proper SDK usage, type
   * safety, assertion logic, and follows basic testing patterns while
   * potentially requiring refinement for production quality.
   *
   * The draft code demonstrates functional correctness but may need
   * improvements in areas such as error handling, edge case coverage,
   * performance optimization, or code organization based on review feedback.
   */
  draft: string;

  /**
   * Code review feedback and improvement recommendations.
   *
   * Detailed quality assessment results identifying potential issues, best
   * practice violations, missing edge cases, or opportunities for code
   * enhancement. The review provides specific, actionable feedback on improving
   * test reliability, readability, maintainability, and comprehensive
   * validation coverage.
   *
   * Review feedback may address concerns such as insufficient error scenarios,
   * unclear test descriptions, missing data validation, performance issues, or
   * deviations from established testing patterns and conventions.
   */
  review?: string;
}
