import { AutoBeAnalyzeDocument } from "./AutoBeAnalyzeDocument";
import { AutoBeAnalyzeFileScenario } from "./AutoBeAnalyzeFileScenario";
import { AutoBeAnalyzeModule } from "./AutoBeAnalyzeModule";

/** Planning document structure for the Analyze phase. */
export interface AutoBeAnalyzeFile extends AutoBeAnalyzeFileScenario {
  /**
   * Document title (bold text, not a heading).
   *
   * The main title of the requirements document that appears at the top of the
   * generated markdown file.
   */
  title: string;

  /**
   * Executive summary of the document.
   *
   * A concise overview (2-3 sentences) describing the purpose and scope of the
   * requirements document.
   */
  summary: string;

  /**
   * Markdown file content. Only write the content of the file. Do not include
   * any questions. This should contain only the contents of the file. Do not
   * write down any questions or appreciation. For example, remove a sentence
   * such as "Is it okay if we proceed with the table of contents? Please let me
   * know if there is anything to add or exclude from the table of contents!"
   *
   * PROHIBITED content in markdown:
   *
   * - Questions to the reader (e.g., "Is there anything else to refine?")
   * - Feedback requests (e.g., "Please review and let me know")
   * - Interactive elements expecting responses
   * - Meta-commentary about the document writing process
   *
   * The markdown must be a complete, standalone deliverable without any
   * conversational elements. If clarification is needed, it should be requested
   * outside the document content.
   */
  content: string;

  /**
   * Hierarchical content structure (Module → Unit → Section).
   *
   * Preserves the three-level hierarchy that the flat `content` markdown loses.
   * Also serves as the source for the Evidence Layer (`document.sections`),
   * which is generated by walking this tree and assigning `sectionId`s.
   *
   * Document-level metadata (`title`, `summary`) lives directly on
   * `AutoBeAnalyzeFile`; this interface represents a single module with
   * `title`, `purpose`, `content`, and `units`.
   */
  module: AutoBeAnalyzeModule;

  /**
   * Two-layer structured document data (per-file).
   *
   * - **Evidence Layer** (`sections`): flat mirror of `module` hierarchy with
   *   `sectionId`s for traceability.
   * - **Semantic Layer** (`srs`): SRS categories extracted from this file's
   *   content via LLM. Every traceable item references back to the Evidence
   *   Layer via `sourceSectionIds`.
   *
   * `null` when:
   *
   * - The file is a TOC (`00-toc.md`) — no substantive requirements to extract.
   * - LLM-based SRS extraction failed after
   *   {@link AutoBeConfigConstant.DOCUMENT_RETRY} attempts — the pipeline
   *   continues without blocking.
   *
   * New downstream consumers should prefer this field over `content`/`module`.
   */
  document: AutoBeAnalyzeDocument | null;
}
