import { AutoBeOpenApi } from "../../openapi/AutoBeOpenApi";

/** @author Kakasoo */
export interface AutoBeRealizeFunction {
  /**
   * OpenAPI endpoint specification
   *
   * Contains the complete OpenAPI specification for this endpoint including
   * HTTP method, path, request/response schemas, and documentation.
   */
  endpoint: AutoBeOpenApi.IEndpoint;

  /**
   * File path where the provider function is generated
   *
   * The relative path to the TypeScript file containing the provider function.
   * Always located under "src/providers/" directory with the function name as
   * filename.
   *
   * Format: "src/providers/${name}.ts" Example:
   * "src/providers/delete__discussionBoard_administrators_$id.ts"
   */
  location: string;

  /**
   * Provider function name
   *
   * The TypeScript function name generated from the OpenAPI path. Follows
   * naming convention: HTTP method + path segments joined by double
   * underscores. Path parameters are prefixed with $.
   *
   * Example: "delete__discussionBoard_administrators_$id"
   */
  name: string;

  /**
   * Generated TypeScript implementation code
   *
   * The complete provider function implementation generated by Realize Agent.
   * Contains production-ready TypeScript code following REALIZE_CODER_TOTAL.md
   * guidelines.
   */
  content: string;
}
