/**
 * @packageDocumentation
 * @module api.functional.autobe.playground.vendors.models
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IAutoBePlaygroundVendorModel } from "@autobe/interface";
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

/**
 * List models registered under a vendor.
 *
 * Returns all model entries for the specified vendor, sorted by creation
 * date in descending order. Model entries are automatically created when
 * a session is created with a new model for this vendor.
 *
 * @param vendorId Target vendor's {@link IAutoBePlaygroundVendor.id }
 * @author Samchon
 * @returns List of vendor model entries
 * @tag Vendor
 *
 * @controller AutoBePlaygroundVendorModelController.index
 * @path GET /autobe/playground/vendors/:vendorId/models
 * @accessor api.functional.autobe.playground.vendors.models.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  vendorId: string & tags.Format<"uuid">,
): Promise<index.Output> {
  return PlainFetcher.fetch(connection, {
    ...index.METADATA,
    template: index.METADATA.path,
    path: index.path(vendorId),
  });
}
export namespace index {
  export type Output = Primitive<Array<IAutoBePlaygroundVendorModel>>;

  export const METADATA = {
    method: "GET",
    path: "/autobe/playground/vendors/:vendorId/models",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (vendorId: string & tags.Format<"uuid">) =>
    `/autobe/playground/vendors/${encodeURIComponent(vendorId?.toString() ?? "null")}/models`;
}

/**
 * Remove a model from a vendor's model list.
 *
 * Permanently deletes the model entry. Sessions that used this model
 * are not affected.
 *
 * @param vendorId Target vendor's {@link IAutoBePlaygroundVendor.id }
 * @param id Target model entry's {@link IAutoBePlaygroundVendorModel.id }
 * @author Samchon
 * @tag Vendor
 *
 * @controller AutoBePlaygroundVendorModelController.erase
 * @path DELETE /autobe/playground/vendors/:vendorId/models/:id
 * @accessor api.functional.autobe.playground.vendors.models.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  vendorId: string & tags.Format<"uuid">,
  id: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(vendorId, id),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/autobe/playground/vendors/:vendorId/models/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    vendorId: string & tags.Format<"uuid">,
    id: string & tags.Format<"uuid">,
  ) =>
    `/autobe/playground/vendors/${encodeURIComponent(vendorId?.toString() ?? "null")}/models/${encodeURIComponent(id?.toString() ?? "null")}`;
}
