import { Controller } from "@nestjs/common";
import { TypedRoute, TypedParam, TypedBody } from "@nestia/core";
import typia, { tags } from "typia";

;
import { IShoppingOrder } from "../../../../api/structures/IShoppingOrder";

;
@Controller("/shopping/customers/:customerId/orders")
export class ShoppingCustomersOrdersController {
    /**
     * Converts the current active cart items into an order application for the customer. Triggers inventory check, locks selected items, snapshots cart for history, and creates an order ready for payment.
     *
     * @param customerId Customer ID initiating the order application.
     * @param body Converts the current active cart items into an order application for the customer. Triggers inventory check, locks selected items, snapshots cart for history, and creates an order ready for payment.
     * @nestia Generated by Nestia - https://github.com/samchon/nestia
    */
    @TypedRoute.Post()
    public async postByCustomerid(
    @TypedParam("customerId")
    customerId: string & tags.Format<"uuid">, 
    @TypedBody()
    body: IShoppingOrder.ICreate): Promise<IShoppingOrder> {
        customerId;
        body;
        return typia.random<IShoppingOrder>();
    }
}
