import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

;
import { IShoppingMember } from "../../../structures/IShoppingMember";
import { IPageIShoppingMember } from "../../../structures/IPageIShoppingMember";
export * as emails from "./emails";
/**
 * Creates a new shopping mall member account. Records member details, links to a citizen record if identity verification has been performed, supports channel-specific membership registration. Email registration is handled separately.
 *
 * @param body Creates a new shopping mall member account. Records member details, links to a citizen record if identity verification has been performed, supports channel-specific membership registration. Email registration is handled separately.
 * @path /shopping/members
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
*/
export async function post(connection: IConnection, body: post.Input): Promise<post.Output> {
    return !!connection.simulate ? post.simulate(connection, body) : PlainFetcher.fetch({
        ...connection,
        headers: {
            ...connection.headers,
            "Content-Type": "application/json"
        }
    }, {
        ...post.METADATA,
        path: post.path(),
        status: null
    }, body);
}
export namespace post {
    export type Input = IShoppingMember.ICreate;
    export type Output = IShoppingMember;
    
    ;
    export const METADATA = {
        method: "POST",
        path: "/shopping/members",
        request: {
            type: "application/json",
            encrypted: false
        },
        response: {
            type: "application/json",
            encrypted: false
        }
    } as const;
    
    ;
    export const path = () => "/shopping/members";
    export const random = (g?: Partial<typia.IRandomGenerator>): IShoppingMember => typia.random<IShoppingMember>(g);
    export const simulate = (connection: IConnection, body: post.Input): Output => {
        const assert = NestiaSimulator.assert({
            method: METADATA.method,
            host: connection.host,
            path: post.path(),
            contentType: "application/json"
        });
        try {
            assert.body(() => typia.assert(body));
        }
        catch (exp) {
            if (!typia.is<HttpError>(exp))
                throw exp;
            return {
                success: false,
                status: exp.status,
                headers: exp.headers,
                data: exp.toJSON().message
            } as any;
        }
        return random("object" === typeof connection.simulate && null !== connection.simulate ? connection.simulate : undefined);
    };
}
/**
 * Retrieves a paginated list of mall members, allowing filtering, sorting, and pagination.
 *
 * @param body Retrieves a paginated list of mall members, allowing filtering, sorting, and pagination.
 * @path /shopping/members
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
*/
export async function patch(connection: IConnection, body: patch.Input): Promise<patch.Output> {
    return !!connection.simulate ? patch.simulate(connection, body) : PlainFetcher.fetch({
        ...connection,
        headers: {
            ...connection.headers,
            "Content-Type": "application/json"
        }
    }, {
        ...patch.METADATA,
        path: patch.path(),
        status: null
    }, body);
}
export namespace patch {
    export type Input = IShoppingMember.IRequest;
    export type Output = IPageIShoppingMember.ISummary;
    
    ;
    export const METADATA = {
        method: "PATCH",
        path: "/shopping/members",
        request: {
            type: "application/json",
            encrypted: false
        },
        response: {
            type: "application/json",
            encrypted: false
        }
    } as const;
    
    ;
    export const path = () => "/shopping/members";
    export const random = (g?: Partial<typia.IRandomGenerator>): IPageIShoppingMember.ISummary => typia.random<IPageIShoppingMember.ISummary>(g);
    export const simulate = (connection: IConnection, body: patch.Input): Output => {
        const assert = NestiaSimulator.assert({
            method: METADATA.method,
            host: connection.host,
            path: patch.path(),
            contentType: "application/json"
        });
        try {
            assert.body(() => typia.assert(body));
        }
        catch (exp) {
            if (!typia.is<HttpError>(exp))
                throw exp;
            return {
                success: false,
                status: exp.status,
                headers: exp.headers,
                data: exp.toJSON().message
            } as any;
        }
        return random("object" === typeof connection.simulate && null !== connection.simulate ? connection.simulate : undefined);
    };
}
/**
 * Retrieves details for a specific member. Includes identity linkage, channels, and other personal info.
 *
 * @param memberId Unique identifier of the member.
 * @path /shopping/members/:memberId
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
*/
export async function getByMemberid(connection: IConnection, memberId: string & tags.Format<"uuid">): Promise<getByMemberid.Output> {
    return !!connection.simulate ? getByMemberid.simulate(connection, memberId) : PlainFetcher.fetch({
        ...connection,
        headers: {
            ...connection.headers,
            "Content-Type": "application/json"
        }
    }, {
        ...getByMemberid.METADATA,
        path: getByMemberid.path(memberId),
        status: null
    });
}
export namespace getByMemberid {
    export type Output = IShoppingMember;
    
    ;
    export const METADATA = {
        method: "GET",
        path: "/shopping/members/:memberId",
        request: null,
        response: {
            type: "application/json",
            encrypted: false
        }
    } as const;
    
    ;
    export const path = (memberId: string & tags.Format<"uuid">) => `/shopping/members/${encodeURIComponent(memberId ?? "null")}`;
    export const random = (g?: Partial<typia.IRandomGenerator>): IShoppingMember => typia.random<IShoppingMember>(g);
    export const simulate = (connection: IConnection, memberId: string & tags.Format<"uuid">): Output => {
        const assert = NestiaSimulator.assert({
            method: METADATA.method,
            host: connection.host,
            path: getByMemberid.path(memberId),
            contentType: "application/json"
        });
        try {
            assert.param("memberId")(() => typia.assert(memberId));
        }
        catch (exp) {
            if (!typia.is<HttpError>(exp))
                throw exp;
            return {
                success: false,
                status: exp.status,
                headers: exp.headers,
                data: exp.toJSON().message
            } as any;
        }
        return random("object" === typeof connection.simulate && null !== connection.simulate ? connection.simulate : undefined);
    };
}
