/**
 * @packageDocumentation
 * @module api.functional.autobe.playground.examples
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type {
  IAutoBePlaygroundExample,
  IAutoBeRpcListener,
  IAutoBeRpcService,
} from "@autobe/interface";
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import { WebSocketConnector } from "tgrid";
import type { Driver } from "tgrid";
import type { Primitive } from "typia";

/**
 * List all available examples from benchmark storage.
 *
 * Returns vendor/project/phase combinations that have pre-recorded data
 * available for mock session creation and direct replay.
 *
 * @author Samchon
 * @returns List of available examples
 * @tag Example
 *
 * @controller AutoBePlaygroundExampleController.index
 * @path GET /autobe/playground/examples
 * @accessor api.functional.autobe.playground.examples.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
): Promise<index.Output> {
  return PlainFetcher.fetch(connection, {
    ...index.METADATA,
    template: index.METADATA.path,
    path: index.path(),
  });
}
export namespace index {
  export type Output = Primitive<IAutoBePlaygroundExample[]>;

  export const METADATA = {
    method: "GET",
    path: "/autobe/playground/examples",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/autobe/playground/examples";
}

/**
 * Replay example data directly via WebSocket.
 *
 * Streams pre-recorded events from the benchmark example storage without
 * creating a database-backed session. Useful for quick preview and QA.
 *
 * @author Samchon
 * @param provider Vendor provider name (e.g. "openai")
 * @param model Model name (e.g. "gpt-4.1")
 * @param project Example project name (e.g. "bbs")
 * @tag Example
 *
 * @controller AutoBePlaygroundExampleSocketController.replay
 * @path /autobe/playground/examples/:provider/:model/:project/replay
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function replay(
  connection: IConnection<replay.Header>,
  provider: string,
  model: string,
  project: string,
  listener: replay.Provider,
): Promise<replay.Output> {
  const url: string = `${connection.host.endsWith("/") ? connection.host.substring(0, connection.host.length - 1) : connection.host}${replay.path(provider, model, project)}`;
  const connector: WebSocketConnector<
    replay.Header,
    replay.Provider,
    replay.Listener
  > = new WebSocketConnector(connection.headers ?? ({} as any), listener);
  await connector.connect(url);
  const driver: Driver<replay.Listener> = connector.getDriver();
  return {
    connector,
    driver,
    reconnect: async () => await connector.connect(url),
  };
}
export namespace replay {
  export type Output = {
    connector: WebSocketConnector<Header, Provider, Listener>;
    driver: Driver<Listener>;
    reconnect: () => Promise<void>;
  };
  export type Header = any;
  export type Provider = IAutoBeRpcListener;
  export type Listener = IAutoBeRpcService;

  export const path = (provider: string, model: string, project: string) =>
    `/autobe/playground/examples/${encodeURIComponent(provider)}/${encodeURIComponent(model)}/${encodeURIComponent(project)}/replay`;
}
