/**
 * @packageDocumentation
 * @module api.functional.autobe.playground.examples
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type {
  IAutoBePlaygroundBenchmark,
  IAutoBePlaygroundReplay,
  IAutoBeRpcListener,
  IAutoBeRpcService,
} from "@autobe/interface";
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import { WebSocketConnector } from "tgrid";
import type { Driver } from "tgrid";

/**
 * List all available examples from benchmark storage.
 *
 * Returns vendor-grouped benchmark data sourced from the pre-computed
 * `benchmark.json`. Each entry contains a vendor identifier, emoji, score,
 * and its replay summaries.
 *
 * @author Samchon
 * @returns List of benchmarks grouped by vendor
 * @tag Example
 *
 * @controller AutoBePlaygroundExampleController.index
 * @path GET /autobe/playground/examples
 * @accessor api.functional.autobe.playground.examples.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(connection: IConnection): Promise<index.Output> {
  return PlainFetcher.fetch(connection, {
    ...index.METADATA,
    template: index.METADATA.path,
    path: index.path(),
  });
}
export namespace index {
  export type Output = Array<IAutoBePlaygroundBenchmark>;

  export const METADATA = {
    method: "GET",
    path: "/autobe/playground/examples",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/autobe/playground/examples";
}

/**
 * Replay example data directly via WebSocket.
 *
 * Streams pre-recorded events from the benchmark example storage without
 * creating a database-backed session. Useful for quick preview and QA.
 *
 * @author Samchon
 * @param query Vendor and project identifiers
 * @tag Example
 *
 * @controller AutoBePlaygroundExampleController.replay
 * @path /autobe/playground/examples/replay
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function replay(
  connection: IConnection<replay.Header>,
  query: replay.Query,
  provider: replay.Provider,
): Promise<replay.Output> {
  const url: string = `${connection.host.endsWith("/") ? connection.host.substring(0, connection.host.length - 1) : connection.host}${replay.path(query)}`;
  const connector: WebSocketConnector<
    replay.Header,
    replay.Provider,
    replay.Listener
  > = new WebSocketConnector(connection.headers ?? ({} as any), provider);
  await connector.connect(url);
  const driver: Driver<replay.Listener> = connector.getDriver();
  return {
    connector,
    driver,
    reconnect: async () => await connector.connect(url),
  };
}
export namespace replay {
  export type Output = {
    connector: WebSocketConnector<Header, Provider, Listener>;
    driver: Driver<Listener>;
    reconnect: () => Promise<void>;
  };
  export type Header = any;
  export type Provider = IAutoBeRpcListener;
  export type Listener = IAutoBeRpcService;
  export type Query = IAutoBePlaygroundReplay.IQuery;

  export const path = (query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/autobe/playground/examples/replay";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}
