import { IAgenticaHistoryJson } from "@agentica/core";
import { IAutoBeTypeScriptCompileResult } from "@autobe/interface";
import { v4 } from "uuid";

import { AutoBeSystemPromptConstant } from "../../constants/AutoBeSystemPromptConstant";
import { AutoBeState } from "../../context/AutoBeState";
import { IAutoBeTestScenarioArtifacts } from "../test/structures/IAutoBeTestScenarioArtifacts";
import { RealizePlannerOutput } from "./orchestrateRealizePlanner";

export const transformRealizeCoderHistories = (
  state: AutoBeState,
  props: RealizePlannerOutput,
  artifacts: IAutoBeTestScenarioArtifacts,
  previous: string | null,
  diagnostics: IAutoBeTypeScriptCompileResult.IDiagnostic[],
): Array<
  IAgenticaHistoryJson.IAssistantMessage | IAgenticaHistoryJson.ISystemMessage
> => {
  if (state.analyze === null)
    return [
      {
        id: v4(),
        created_at: new Date().toISOString(),
        type: "systemMessage",
        text: [
          "Requirement analysis is not yet completed.",
          "Don't call the any tool function,",
          "but say to process the requirement analysis.",
        ].join(" "),
      },
    ];
  else if (state.prisma === null)
    return [
      {
        id: v4(),
        created_at: new Date().toISOString(),
        type: "systemMessage",
        text: [
          "Prisma DB schema generation is not yet completed.",
          "Don't call the any tool function,",
          "but say to process the Prisma DB schema generation.",
        ].join(" "),
      },
    ];
  else if (state.analyze.step !== state.prisma.step)
    return [
      {
        id: v4(),
        created_at: new Date().toISOString(),
        type: "systemMessage",
        text: [
          "Prisma DB schema generation has not been updated",
          "for the latest requirement analysis.",
          "Don't call the any tool function,",
          "but say to re-process the Prisma DB schema generation.",
        ].join(" "),
      },
    ];
  else if (state.prisma.compiled.type !== "success")
    return [
      {
        id: v4(),
        created_at: new Date().toISOString(),
        type: "systemMessage",
        text: [
          "Prisma DB schema generation has not been updated",
          "for the latest requirement analysis.",
          "Don't call the any tool function,",
          "but say to re-process the Prisma DB schema generation.",
        ].join(" "),
      },
    ];
  else if (state.interface === null)
    return [
      {
        id: v4(),
        created_at: new Date().toISOString(),
        type: "systemMessage",
        text: [
          "Interface generation is not yet completed.",
          "Don't call the any tool function,",
          "but say to process the interface generation.",
        ].join(" "),
      },
    ];

  return [
    {
      id: v4(),
      created_at: new Date().toISOString(),
      type: "systemMessage",
      text: AutoBeSystemPromptConstant.REALIZE_CODER,
    },
    {
      id: v4(),
      created_at: new Date().toISOString(),
      type: "systemMessage",
      text: AutoBeSystemPromptConstant.REALIZE_CODER_TYPESCRIPT,
    },
    {
      id: v4(),
      created_at: new Date().toISOString(),
      type: "systemMessage",
      text: AutoBeSystemPromptConstant.REALIZE_CODER_PRISMA,
    },
    {
      id: v4(),
      created_at: new Date().toISOString(),
      type: "systemMessage",
      text: AutoBeSystemPromptConstant.REALIZE_CODER_BROWSER,
    },
    {
      id: v4(),
      created_at: new Date().toISOString(),
      type: "systemMessage",
      text: AutoBeSystemPromptConstant.REALIZE_CODER_TYPIA,
    },
    {
      id: v4(),
      created_at: new Date().toISOString(),
      type: "systemMessage",
      text: [
        "# Prisma Schemas",
        "```json",
        JSON.stringify(state.prisma.schemas),
        "```",
        "# ℹ️ How to Use the Above Prisma Schemas",
        "- These Prisma schemas are extracted from your actual `schema.prisma` file.",
        "- You must always consult the schema when writing any `update`, `create`, or `select` logic.",
        "- Pay special attention to:",
        "  1. **Which fields are required, optional, or nullable**",
        "  2. **Which fields are scalar vs. relation fields** (e.g., `role_id` vs. `role`)",
        "  3. **Which fields can be updated directly** (scalar fields) vs. **indirectly** (via `connect`, `disconnect`, `set` in nested relation objects)",
        "- For relation fields like `user_role_id`, do not assign it directly — instead, use the relation name (e.g., `role: { connect: { id: ... } }`).",
        "- The type definitions generated by Prisma (e.g., `Prisma.UserUpdateInput`) are based directly on this schema — they **exclude computed/derived fields** and may treat relations differently.",
        "- When in doubt, cross-reference your assignment logic with this schema to avoid `TS2322`, `TS2339`, and other structural typing errors.",
        "- ❗Never assume a field exists in the update input just because it appears in the model. Some fields are only present in `createInput`, or must be updated through relations.",
        "",
        // "# Prisma Types",
        // "```json",
        // JSON.stringify(state.prisma.compiled.nodeModules),
        // "```",
        "# SDK",
        "",
        "The following is the SDK for the API. Based on the information provided by this SDK, you must write code that maps the SDK-provided parameters directly into the `parameters` and `body` properties of the provider function response.",
        "If there are no parameters, define `parameters` as `Record<string, never>`. Similarly, if there is no body, define `body` as `Record<string, never>`.",
        "**Every function must be implemented to accept both `parameters` and `body`, without exception.**",
        "If any required type information is referenced in the SDK, refer to the definitions in the DTO section.",
        "",
        "```json",
        JSON.stringify(artifacts.sdk),
        "```",
        "",
        "# DTO",
        "if you want to import this files, write this: 'import { something } from '../api/structures/something';'",
        "",
        "```json",
        JSON.stringify(artifacts.dto),
        "```",
        "# Document",
        "```json",
        JSON.stringify(artifacts.document),
        "```",
      ].join("\n"),
    },
    ...(previous !== null
      ? [
          {
            id: v4(),
            created_at: new Date().toISOString(),
            type: "assistantMessage",
            text: [
              "The code you previously wrote is as follows:",
              "```typescript",
              previous,
              "```",
              "",
              "However, the following errors occurred:",
              "```json",
              JSON.stringify(diagnostics),
              "",
              "Please take these facts into account when writing the next version of the code.",
              "",
              "💡 **Tip Regarding Date Type Errors**",
              "",
              "If you encounter errors related to the `Date` type, a common fix is to call the `.toISOString()` method on the `Date` object and treat it as a `string`.",
              "This approach resolves most type-related issues.",
              "Please note that in our defined types—especially in properties involving dates—and in all `Date` or `DateTime` fields from Prisma,",
              "**dates must be handled as `string` values**, not as native `Date` objects.",
              "Always ensure date values conform to the expected format:",
              "",
              "```ts",
              "string & tags.Format<'date-time'>",
              "```",
              "",
              "```ts",
              "// If there is some Date type property...",
              "DateProp.toISOString(); // GOOD!",
              "DateProp as string; // BAD!",
              "```",
            ].join("\n"),
          } as const,
        ]
      : []),
    {
      id: v4(),
      created_at: new Date().toISOString(),
      type: "systemMessage",
      text: [
        previous
          ? "Modify the previous code to reflect the following operation."
          : "Write new code based on the following operation.",
        "```json",
        JSON.stringify(props),
        "```",
      ].join("\n"),
    },
  ];
};
