import { Controller } from "@nestjs/common";
import { TypedRoute, TypedParam } from "@nestia/core";
import typia, { tags } from "typia";

;
import { IShoppingCart } from "../../../api/structures/IShoppingCart";

;
@Controller("/shopping/carts/:customerId")
export class ShoppingCartsController {
    /**
     * Retrieves the given customer's entire shopping cart, including all currently active (not deleted/published) commodities and their chosen options.
     *
     * @param customerId Unique customer ID (owner of the cart).
     * @nestia Generated by Nestia - https://github.com/samchon/nestia
    */
    @TypedRoute.Get()
    public async getByCustomerid(
    @TypedParam("customerId")
    customerId: string & tags.Format<"uuid">): Promise<IShoppingCart> {
        customerId;
        return typia.random<IShoppingCart>();
    }
}
