import {
  AutoBeDatabaseGroup,
  AutoBeDatabaseGroupRevise,
} from "@autobe/interface";
import { StringUtil } from "@autobe/utils";
import { IValidation } from "typia";

export namespace AutoBeDatabaseGroupReviewProgrammer {
  /**
   * Validates the group revisions.
   *
   * This function:
   *
   * 1. Validates that authorization groups cannot be created, updated, or erased
   * 2. Validates that create operations don't target existing namespaces
   * 3. Validates that update/erase operations reference existing namespaces
   *
   * @param props Validation context with errors array, current groups, and
   *   revisions
   */
  export const validate = (props: {
    errors: IValidation.IError[];
    path: string;
    groups: AutoBeDatabaseGroup[];
    revises: AutoBeDatabaseGroupRevise[];
  }): void => {
    const groupMap: Map<string, AutoBeDatabaseGroup> = new Map(
      props.groups.map((g) => [g.namespace, g]),
    );
    const authorizationNamespaces: Set<string> = new Set(
      props.groups
        .filter((g) => g.kind === "authorization")
        .map((g) => g.namespace),
    );

    props.revises.forEach((revise, i) => {
      if (revise.type === "create") {
        // Cannot create authorization group
        if (revise.group.kind === "authorization") {
          props.errors.push({
            path: `${props.path}[${i}].group.kind`,
            expected: '"domain"',
            value: revise.group.kind,
            description: StringUtil.trim`
              Cannot create a group with kind "authorization".

              Authorization groups are generated by the Group Agent and cannot be
              created during review. Only domain groups can be created.

              Fix: Change the kind to "domain" or remove this create operation.
            `,
          });
        }
        // Cannot create if namespace already exists
        if (groupMap.has(revise.group.namespace) === true) {
          props.errors.push({
            path: `${props.path}[${i}].group.namespace`,
            expected: "non-existing namespace",
            value: revise.group.namespace,
            description: StringUtil.trim`
              Group "${revise.group.namespace}" already exists.

              Fix: Choose a different namespace for the new group, or remove this create operation.
            `,
          });
        }
      } else if (revise.type === "update") {
        // Cannot update to authorization kind
        if (revise.group.kind === "authorization") {
          props.errors.push({
            path: `${props.path}[${i}].group.kind`,
            expected: '"domain"',
            value: revise.group.kind,
            description: StringUtil.trim`
              Cannot update a group to kind "authorization".

              Authorization groups are protected and cannot be modified during review.
              Only domain groups can be updated.

              Fix: Remove this update operation targeting the authorization group, or change the kind to "domain".
            `,
          });
        }
        // Cannot update authorization group
        if (authorizationNamespaces.has(revise.originalNamespace) === true) {
          props.errors.push({
            path: `${props.path}[${i}].originalNamespace`,
            expected: "domain group namespace",
            value: revise.originalNamespace,
            description: StringUtil.trim`
              Cannot update authorization group "${revise.originalNamespace}".

              Authorization groups are protected and cannot be modified during review.
              Only domain groups can be updated.

              Fix: Remove this update operation targeting the authorization group.
            `,
          });
        }
        // Cannot update non-existing group
        if (groupMap.has(revise.originalNamespace) === false) {
          props.errors.push({
            path: `${props.path}[${i}].originalNamespace`,
            expected: Array.from(groupMap.keys())
              .map((s) => JSON.stringify(s))
              .join(" | "),
            value: revise.originalNamespace,
            description: StringUtil.trim`
              Group "${revise.originalNamespace}" does not exist.

              Fix: Ensure the originalNamespace matches an existing group's namespace.

              Valid namespaces:
              ${props.groups.map((g) => `- ${g.namespace}`).join("\n")}
            `,
          });
        }
        // Cannot update to a namespace that already exists on another group
        if (
          groupMap.has(revise.group.namespace) === true &&
          revise.group.namespace !== revise.originalNamespace
        ) {
          props.errors.push({
            path: `${props.path}[${i}].group.namespace`,
            expected: "unique namespace",
            value: revise.group.namespace,
            description: StringUtil.trim`
              Cannot update group "${revise.originalNamespace}" to namespace "${revise.group.namespace}" because another group already uses that namespace.
              Each group namespace must be unique.
              
              Fix: Choose a namespace that is not already used by another group.
            `,
          });
        }
      } else if (revise.type === "erase") {
        // Cannot erase authorization group
        if (authorizationNamespaces.has(revise.namespace) === true) {
          props.errors.push({
            path: `${props.path}[${i}].namespace`,
            expected: "domain group namespace",
            value: revise.namespace,
            description: StringUtil.trim`
              Cannot erase authorization group "${revise.namespace}".

              Authorization groups are protected and cannot be deleted during review.
              Only domain groups can be erased.

              Fix: Remove this erase operation targeting the authorization group.
            `,
          });
        }
        // Cannot erase non-existing group
        if (groupMap.has(revise.namespace) === false) {
          props.errors.push({
            path: `${props.path}[${i}].namespace`,
            expected: Array.from(groupMap.keys())
              .map((s) => JSON.stringify(s))
              .join(" | "),
            value: revise.namespace,
            description: StringUtil.trim`
              Group "${revise.namespace}" does not exist.

              Fix: Ensure the namespace matches an existing group's namespace.

              Valid namespaces:
              ${props.groups.map((g) => `- ${g.namespace}`).join("\n")}
            `,
          });
        }
      }
    });
  };

  /**
   * Applies the group revisions to produce the final group list.
   *
   * @param props Execution context with groups and revisions
   * @returns The modified groups
   */
  export const execute = (props: {
    groups: AutoBeDatabaseGroup[];
    revises: AutoBeDatabaseGroupRevise[];
  }): AutoBeDatabaseGroup[] => {
    const groupMap = new Map<string, AutoBeDatabaseGroup>(
      props.groups.map((g) => [g.namespace, g]),
    );

    for (const revise of props.revises) {
      if (revise.type === "create") {
        if (groupMap.has(revise.group.namespace) === false)
          groupMap.set(revise.group.namespace, revise.group);
      } else if (revise.type === "update") {
        if (
          groupMap.has(revise.originalNamespace) === true &&
          groupMap.has(revise.group.namespace) === false
        ) {
          groupMap.delete(revise.originalNamespace);
          groupMap.set(revise.group.namespace, revise.group);
        }
      } else if (revise.type === "erase") {
        if (groupMap.has(revise.namespace) === true)
          groupMap.delete(revise.namespace);
      } else {
        revise satisfies never;
      }
    }

    return Array.from(groupMap.values());
  };
}
