import { IConnection, HttpError } from "@nestia/fetcher";
import typia, { tags } from "typia";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

;
import { IShoppingOrderPublish } from "../../../../structures/IShoppingOrderPublish";
/**
 * Handles payment application for a given order, including cash, deposit, mileage, coupons, and asynchronous (virtual account) methods. Records payment details and changes order state. Used for both payment and cancellation workflows.
 *
 * @param orderId Unique identifier of the order.
 * @param body Handles payment application for a given order, including cash, deposit, mileage, coupons, and asynchronous (virtual account) methods. Records payment details and changes order state. Used for both payment and cancellation workflows.
 * @path /shopping/orders/:orderId/publishes
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
*/
export async function postByOrderid(connection: IConnection, orderId: string & tags.Format<"uuid">, body: postByOrderid.Input): Promise<postByOrderid.Output> {
    return !!connection.simulate ? postByOrderid.simulate(connection, orderId, body) : PlainFetcher.fetch({
        ...connection,
        headers: {
            ...connection.headers,
            "Content-Type": "application/json"
        }
    }, {
        ...postByOrderid.METADATA,
        path: postByOrderid.path(orderId),
        status: null
    }, body);
}
export namespace postByOrderid {
    export type Input = IShoppingOrderPublish.ICreate;
    export type Output = IShoppingOrderPublish;
    
    ;
    export const METADATA = {
        method: "POST",
        path: "/shopping/orders/:orderId/publishes",
        request: {
            type: "application/json",
            encrypted: false
        },
        response: {
            type: "application/json",
            encrypted: false
        }
    } as const;
    
    ;
    export const path = (orderId: string & tags.Format<"uuid">) => `/shopping/orders/${encodeURIComponent(orderId ?? "null")}/publishes`;
    export const random = (g?: Partial<typia.IRandomGenerator>): IShoppingOrderPublish => typia.random<IShoppingOrderPublish>(g);
    export const simulate = (connection: IConnection, orderId: string & tags.Format<"uuid">, body: postByOrderid.Input): Output => {
        const assert = NestiaSimulator.assert({
            method: METADATA.method,
            host: connection.host,
            path: postByOrderid.path(orderId),
            contentType: "application/json"
        });
        try {
            assert.param("orderId")(() => typia.assert(orderId));
            assert.body(() => typia.assert(body));
        }
        catch (exp) {
            if (!typia.is<HttpError>(exp))
                throw exp;
            return {
                success: false,
                status: exp.status,
                headers: exp.headers,
                data: exp.toJSON().message
            } as any;
        }
        return random("object" === typeof connection.simulate && null !== connection.simulate ? connection.simulate : undefined);
    };
}
