import { Controller } from "@nestjs/common";
import { TypedRoute, TypedParam, TypedBody } from "@nestia/core";
import typia, { tags } from "typia";

;
import { IShoppingCouponTicket } from "../../../../api/structures/IShoppingCouponTicket";

;
@Controller("/shopping/customers/:customerId/coupon-tickets")
export class ShoppingCustomersCoupon_ticketsController {
    /**
     * Allocates/assigns a coupon (public or code) to a customer as a coupon ticket. Record validity and restrict usage as necessary.
     *
     * @param customerId Customer ID receiving the coupon ticket.
     * @param body Allocates/assigns a coupon (public or code) to a customer as a coupon ticket. Record validity and restrict usage as necessary.
     * @nestia Generated by Nestia - https://github.com/samchon/nestia
    */
    @TypedRoute.Post()
    public async postByCustomerid(
    @TypedParam("customerId")
    customerId: string & tags.Format<"uuid">, 
    @TypedBody()
    body: IShoppingCouponTicket.ICreate): Promise<IShoppingCouponTicket> {
        customerId;
        body;
        return typia.random<IShoppingCouponTicket>();
    }
}
